

### Description
GET http://103.184.122.170/api/snmp/signalProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/signalProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "signalName": "",
    "mgcProtocolType": "",
    "mgc1Address": "",
    "mgc1Port": "",
    "mgc2Address": "",
    "mgc2Port": "",
    "mgc3Address": "",
    "mgc3Port": "",
    "primaryDNS": "",
    "secondaryDNS": "",
    "sipRegistrationAddress": "",
    "sipRegistrationPort": "",
    "sipServerAddress": "",
    "sipServerPort": "",
    "sipTimeOut": "",
    "keepAlive": "",
    "aliveInterval": "",
    "aliveTime": "",
    "signalProfileAction": ""
}






### Description
GET http://103.184.122.170/api/snmp/potsUserCfgTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/potsUserCfgTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "potsEnable": "",
    "telNum": "",
    "bindingSignalName": "",
    "signalVlan": "",
    "svlanEnable": "",
    "svlanId": "",
    "svlanCosFor5516": "",
    "cvalnCosFor5516": "",
    "voiceDomain": "",
    "protocolPort": "",
    "userNameSipTelNum": "",
    "sipUserName": "",
    "sipPassword": "",
    "bindingPotsCfgProfileName": "",
    "potsUserCfgAction": ""
}






### Description
GET http://103.184.122.170/api/snmp/onuVoiceCfgTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/onuVoiceCfgTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ipCfgType": "",
    "staticIPAddress": "",
    "staticIPMask": "",
    "staticIPGateway": "",
    "pppoeUserName": "",
    "pppoePassword": "",
    "dhcpOption60Enable": "",
    "dhcpOption60Suffix": "",
    "bindingVoicePlatformProfileName": "",
    "voiceCfgAction": ""
}






### Description
GET http://103.184.122.170/api/snmp/voicePlatformProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/voicePlatformProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "voicePlatformProfileName": "",
    "rtpNameFiexedPart": "",
    "rtpBeginValue": "",
    "rtpEndValue": "",
    "rtpStepValue": "",
    "rtpNameFill": "",
    "digitmapStartTimer": "",
    "digitmapShortTimer": "",
    "digitmapLongTimer": "",
    "dialMapNotifyImmediately": "",
    "vbdEnable": "",
    "packetIntervalOut": "",
    "packetIntervalIn": "",
    "codeType": "",
    "platformProfileAction": ""
}






### Description
GET http://103.184.122.170/api/snmp/potsCfgProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/potsCfgProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "potsCfgProfileName": "",
    "voiceCoder": "",
    "faxMode": "",
    "slienceSwitch": "",
    "echoCancel": "",
    "inputGain": "",
    "outputGain": "",
    "dtmfMode": "",
    "faxCtrlMode": "",
    "potsProfileAction": ""
}






