### DMT interface physical layer actuals information<br/><br/>table.
GET http://103.184.122.170/api/snmp/adslLineDMTTable
Authorization: Bearer {{token}}

### DMT interface physical layer actuals information<br/><br/>table for the central office.
GET http://103.184.122.170/api/snmp/adslAtucDMTPhysTable
Authorization: Bearer {{token}}

### DMT interface physical layer actuals information<br/><br/>table for the remote unit.
GET http://103.184.122.170/api/snmp/adslAturDMTPhysTable
Authorization: Bearer {{token}}

### This table contains the target DMT specific configuration<br/><br/>parameters for the physical layer before initialization.
GET http://103.184.122.170/api/snmp/adslLineDMTConfProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/adslLineDMTConfProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "adslAtucDMTConfFreqBins": 0,
    "adslAturDMTConfFreqBins": 0,
    "adslLineDMTConfEOC": 1
}

