### A table of information about possible alarms on the system,<br/>and how they have been modelled.
GET http://localhost/api/snmp/alarmModelTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/alarmModelTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alarmModelNotificationId": "zeroDotZero",
    "alarmModelVarbindIndex": 0,
    "alarmModelVarbindValue": 0,
    "alarmModelDescription": 0,
    "alarmModelSpecificPointer": "zeroDotZero",
    "alarmModelVarbindSubtree": "zeroDotZero",
    "alarmModelResourcePrefix": "zeroDotZero",
    "alarmModelRowStatus": ""
}

### A table of Active Alarms entries.
GET http://localhost/api/snmp/alarmActiveTable
Authorization: Bearer {{token}}

### A table of variables to go with active alarm entries.
GET http://localhost/api/snmp/alarmActiveVariableTable
Authorization: Bearer {{token}}

### This table represents the alarm statistics<br/>information.
GET http://localhost/api/snmp/alarmActiveStatsTable
Authorization: Bearer {{token}}

