### A table that contains information about every<br/>Aggregator that is associated with this System.
GET http://localhost/api/snmp/dot3adAggTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/dot3adAggTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dot3adAggActorSystemPriority": "",
    "dot3adAggActorAdminKey": "",
    "dot3adAggCollectorMaxDelay": ""
}

### A table that contains a list of all the ports<br/>associated with each Aggregator.
GET http://localhost/api/snmp/dot3adAggPortListTable
Authorization: Bearer {{token}}

### A table that contains Link Aggregation Control<br/>configuration information about every<br/>Aggregation Port associated with this device.<br/>A row appears in this table for each physical port.
GET http://localhost/api/snmp/dot3adAggPortTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/dot3adAggPortTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "dot3adAggPortActorSystemPriority": "",
    "dot3adAggPortActorAdminKey": "",
    "dot3adAggPortActorOperKey": "",
    "dot3adAggPortPartnerAdminSystemPriority": "",
    "dot3adAggPortPartnerAdminSystemID": "",
    "dot3adAggPortPartnerAdminKey": "",
    "dot3adAggPortActorPortPriority": "",
    "dot3adAggPortPartnerAdminPort": "",
    "dot3adAggPortPartnerAdminPortPriority": "",
    "dot3adAggPortActorAdminState": "",
    "dot3adAggPortPartnerAdminState": ""
}

### A table that contains Link Aggregation information<br/>about every port that is associated with this device.<br/>A row appears in this table for each physical port.
GET http://localhost/api/snmp/dot3adAggPortStatsTable
Authorization: Bearer {{token}}

### A table that contains Link Aggregation debug<br/>information about every port that is associated with<br/>this device.  A row appears in this table for each<br/>physical port.
GET http://localhost/api/snmp/dot3adAggPortDebugTable
Authorization: Bearer {{token}}

