### A table of system level information for each interface<br/><br/>supported by the MAC security entity.  An entry appears in this<br/><br/>table for each interface with MAC security capability in this<br/><br/>system.<br/><br/><br/><br/>For the writeable objects in this table, the configured value<br/><br/>shall be stored in persistent memory and remain unchanged across<br/><br/>a re-initialization of the management system of the entity.
GET http://103.184.122.170/api/snmp/secyIfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/secyIfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "secyIfProtectFramesEnable": 1,
    "secyIfValidateFrames": 3,
    "secyIfReplayProtectEnable": 1,
    "secyIfReplayProtectWindow": 0,
    "secyIfCurrentCipherSuite": "",
    "secyIfAdminPt2PtMAC": 3,
    "secyIfIncludeSCIEnable": 2,
    "secyIfUseESEnable": 2,
    "secyIfUseSCBEnable": 2
}

### A table for providing information about the status of each<br/><br/>transmitting SC supported by the MAC security entity.
GET http://103.184.122.170/api/snmp/secyTxSCTable
Authorization: Bearer {{token}}

### A table for providing information about the status of each<br/><br/>transmitting SA supported by the MAC security entity.
GET http://103.184.122.170/api/snmp/secyTxSATable
Authorization: Bearer {{token}}

### A table for providing information about the status of each<br/><br/>receiving SC supported by the MAC security entity.
GET http://103.184.122.170/api/snmp/secyRxSCTable
Authorization: Bearer {{token}}

### A table for providing information about the status of each<br/><br/>receiving SA supported by the MAC security entity.
GET http://103.184.122.170/api/snmp/secyRxSATable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/secyRxSATable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "secyRxSANextPN": ""
}

### The table of selectable cipher suites for the MAC security<br/><br/>entity.<br/><br/><br/><br/>For the writeable objects in this table, the configured value<br/><br/>shall be stored in persistent memory and remain unchanged across<br/><br/>a re-initialization of the management system of the entity.
GET http://103.184.122.170/api/snmp/secyCipherSuiteTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/secyCipherSuiteTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "secyCipherSuiteId": "",
    "secyCipherSuiteName": "",
    "secyCipherSuiteCapability": "",
    "secyCipherSuiteProtection": "{ integrity",
    "secyCipherSuiteProtectionOffset": 0,
    "secyCipherSuiteDataLengthChange": "",
    "secyCipherSuiteICVLength": "",
    "secyCipherSuiteRowStatus": ""
}

### A table that contains the statistics objects for each<br/><br/>transmitting SA in the MAC security entity.
GET http://103.184.122.170/api/snmp/secyTxSAStatsTable
Authorization: Bearer {{token}}

### A table that contains statistics information for each<br/><br/>transmitting SC in the MAC security entity.
GET http://103.184.122.170/api/snmp/secyTxSCStatsTable
Authorization: Bearer {{token}}

### A table that contains the statistics objects for each<br/><br/>receiving SA in the MAC security entity.
GET http://103.184.122.170/api/snmp/secyRxSAStatsTable
Authorization: Bearer {{token}}

### A table for the statistics information of each receiving SC<br/><br/>supported by the MAC security entity.
GET http://103.184.122.170/api/snmp/secyRxSCStatsTable
Authorization: Bearer {{token}}

### A table for the statistics information of each SecY supported by<br/><br/>the MAC security entity.
GET http://103.184.122.170/api/snmp/secyStatsTable
Authorization: Bearer {{token}}

