### A table of ITU Alarm information for possible alarms<br/><br/>on the system.
GET http://103.184.122.170/api/snmp/ituAlarmTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/ituAlarmTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ituAlarmEventType": "",
    "ituAlarmProbableCause": "",
    "ituAlarmAdditionalText": "",
    "ituAlarmGenericModel": ""
}

### A table of ITU information for active alarms entries.
GET http://103.184.122.170/api/snmp/ituAlarmActiveTable
Authorization: Bearer {{token}}

### This table represents the ITU alarm statistics<br/><br/>information.
GET http://103.184.122.170/api/snmp/ituAlarmActiveStatsTable
Authorization: Bearer {{token}}

