### A table of transport addresses to be used in the generation<br/><br/>of SNMP messages.
GET http://localhost/api/snmp/snmpTargetAddrTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/snmpTargetAddrTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "snmpTargetAddrTDomain": "",
    "snmpTargetAddrTAddress": "",
    "snmpTargetAddrTimeout": 1500,
    "snmpTargetAddrRetryCount": 3,
    "snmpTargetAddrTagList": "",
    "snmpTargetAddrParams": "",
    "snmpTargetAddrStorageType": "",
    "snmpTargetAddrRowStatus": ""
}

### A table of SNMP target information to be used<br/><br/>in the generation of SNMP messages.
GET http://localhost/api/snmp/snmpTargetParamsTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/snmpTargetParamsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "snmpTargetParamsMPModel": "",
    "snmpTargetParamsSecurityModel": "",
    "snmpTargetParamsSecurityName": "",
    "snmpTargetParamsSecurityLevel": "",
    "snmpTargetParamsStorageType": "",
    "snmpTargetParamsRowStatus": ""
}

