### A list of Mac-Layer Token Ring statistics<br/><br/>entries.
GET http://103.184.122.170/api/snmp/tokenRingMLStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/tokenRingMLStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tokenRingMLStatsDataSource": "",
    "tokenRingMLStatsOwner": "",
    "tokenRingMLStatsStatus": ""
}

### A list of promiscuous Token Ring statistics<br/><br/>entries.
GET http://103.184.122.170/api/snmp/tokenRingPStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/tokenRingPStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tokenRingPStatsDataSource": "",
    "tokenRingPStatsOwner": "",
    "tokenRingPStatsStatus": ""
}

### A list of Mac-Layer Token Ring statistics<br/><br/>entries.
GET http://103.184.122.170/api/snmp/tokenRingMLHistoryTable
Authorization: Bearer {{token}}

### A list of promiscuous Token Ring statistics<br/><br/>entries.
GET http://103.184.122.170/api/snmp/tokenRingPHistoryTable
Authorization: Bearer {{token}}

### A list of ringStation table control entries.
GET http://103.184.122.170/api/snmp/ringStationControlTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/ringStationControlTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ringStationControlOwner": "",
    "ringStationControlStatus": ""
}

### A list of ring station entries.  An entry will<br/><br/>exist for each station that is now or has<br/><br/>previously been detected as physically present on<br/><br/>this ring.
GET http://103.184.122.170/api/snmp/ringStationTable
Authorization: Bearer {{token}}

### A list of ring station entries for stations in<br/><br/>the ring poll, ordered by their ring-order.
GET http://103.184.122.170/api/snmp/ringStationOrderTable
Authorization: Bearer {{token}}

### A list of ring station configuration control<br/><br/>entries.
GET http://103.184.122.170/api/snmp/ringStationConfigControlTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/ringStationConfigControlTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ringStationConfigControlRemove": "",
    "ringStationConfigControlUpdateStats": ""
}

### A list of configuration entries for stations on a<br/><br/>ring monitored by this probe.
GET http://103.184.122.170/api/snmp/ringStationConfigTable
Authorization: Bearer {{token}}

### A list of source routing statistics entries.
GET http://103.184.122.170/api/snmp/sourceRoutingStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/sourceRoutingStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sourceRoutingStatsOwner": "",
    "sourceRoutingStatsStatus": ""
}

