### This table specifies information for configuring<br/><br/>and monitoring Virtual Private Lan Services(VPLS).
GET http://localhost/api/snmp/vplsConfigTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/vplsConfigTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "vplsConfigName": 0,
    "vplsConfigDescr": 0,
    "vplsConfigAdminStatus": 2,
    "vplsConfigMacLearning": 1,
    "vplsConfigDiscardUnknownDest": 2,
    "vplsConfigMacAging": 1,
    "vplsConfigFwdFullHighWatermark": 95,
    "vplsConfigFwdFullLowWatermark": 90,
    "vplsConfigRowStatus": "",
    "vplsConfigMtu": 1518,
    "vplsConfigServiceType": 1,
    "vplsConfigStorageType": 2
}

### This table provides information for monitoring<br/><br/>Virtual Private Lan Services(VPLS).
GET http://localhost/api/snmp/vplsStatusTable
Authorization: Bearer {{token}}

### This table provides an association between a<br/><br/>VPLS service and the corresponding Pseudo<br/><br/>Wires. A service can have more than one Pseudo<br/><br/>Wire association. Pseudo Wires are defined in<br/><br/>the pwTable
GET http://localhost/api/snmp/vplsPwBindTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/vplsPwBindTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "vplsPwBindConfigType": "",
    "vplsPwBindType": "",
    "vplsPwBindRowStatus": "",
    "vplsPwBindStorageType": 2
}

### This table specifies information for configuring<br/><br/>BGP Auto-discovery parameters for a given Vpls service.
GET http://localhost/api/snmp/vplsBgpADConfigTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/vplsBgpADConfigTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "vplsBgpADConfigRouteDistinguisher": "",
    "vplsBgpADConfigPrefix": 0,
    "vplsBgpADConfigVplsId": "",
    "vplsBgpADConfigRowStatus": ""
}

### This table specifies the list of Route Targets<br/><br/>imported or exported by BGP during auto-discovery of VPLS.
GET http://localhost/api/snmp/vplsBgpRteTargetTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/vplsBgpRteTargetTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "vplsBgpRteTargetRTType": "",
    "vplsBgpRteTargetRT": "",
    "vplsBgpRteTargetRTRowStatus": ""
}

