### A table entry containing status information of<br/><br/>files synchronization from master card to slave card.
GET http://103.184.122.170/api/snmp/zxAnFileSyncStatusTable
Authorization: Bearer {{token}}

### A table entry containing file information .
GET http://103.184.122.170/api/snmp/zxAnFileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnFileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnFileOperation": ""
}

### The file list table.<br/><br/>This table is added to support the new index of the NE files:<br/><br/>'rack-shelf-slot-devType-devId-directory-name'.
GET http://103.184.122.170/api/snmp/zxAnFileListTable
Authorization: Bearer {{token}}

