### This table provides the mechanism to control user management.
GET http://localhost/api/snmp/zxAnCliUserConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnCliUserConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCliUserConfName": "",
    "zxAnCliUserConfPwd": "",
    "zxAnCliUserConfPriority": "",
    "zxAnCliUserConfAdminStatus": "",
    "zxAnCliUserConfNewPwd": "",
    "zxAnCliUserConfLoginStartTime": "",
    "zxAnCliUserConfLoginEndTime": "",
    "zxAnCliUserConfExpiredDate": "",
    "zxAnCliUserConfRowStatus": ""
}

### This table provides information of users that are currently logging<br/><br/>on this device
GET http://localhost/api/snmp/zxAnCliActiveUserTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnCliActiveUserTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCliActiveUserRowStatus": ""
}

