### VND resource profile table.<br/><br/>This table is valid only in VND 0.
GET http://localhost/api/snmp/zxAnVndResProfileTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnVndResProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVndResUpperThresh": "",
    "zxAnVndResProfileRowStatus": ""
}

### VND resource profile configuration table.<br/><br/>This table is valid only in VND 0.
GET http://localhost/api/snmp/zxAnVndResProfileConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnVndResProfileConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVndResConfPrfName": ""
}

### VND Resource Statistics Table.<br/><br/>This table is valid only in VND 0.
GET http://localhost/api/snmp/zxAnVndResStatsTable
Authorization: Bearer {{token}}

### VND Current Resource Statistics Table.<br/><br/>This table is valid in every VND and only can get current VND<br/><br/>resource.
GET http://localhost/api/snmp/zxAnVndCurrResStatsTable
Authorization: Bearer {{token}}

### VND interface assigned information table.<br/><br/>This table is valid in every VND.
GET http://localhost/api/snmp/zxAnVndIfAssignedInfoTable
Authorization: Bearer {{token}}

### Assignable card information table.<br/><br/>This table is valid only in VND 0.
GET http://localhost/api/snmp/zxAnVndAssignableCardTable
Authorization: Bearer {{token}}

