### RIP redistribution table.
GET http://103.184.122.170/api/snmp/zxAnRipRedistributionTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnRipRedistributionTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRipRedistributionMetric": "",
    "zxAnRipRedistributionRowStatus": ""
}

### RIP network table.
GET http://103.184.122.170/api/snmp/zxAnRipNetworkTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnRipNetworkTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRipNetworkIpPfxLen": "",
    "zxAnRipNetworkRowStatus": ""
}

### RIP route advertisement table.
GET http://103.184.122.170/api/snmp/zxAnRipAdvertiseRouteTable
Authorization: Bearer {{token}}

