### Uplink port protection table.
GET http://103.184.122.170/api/snmp/zxAnSecUplinkProtectionTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSecUplinkProtectionTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSecUplinkProtectionEnable": ""
}

### When the value of 'zxAnSecGlbVlanIsolationEnable' is enabled, the<br/><br/>table allowed be created, deleted, or the table can not be created<br/><br/>and deleted.
GET http://103.184.122.170/api/snmp/zxAnSecVlanCommunicateTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSecVlanCommunicateTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSecVlanCommunicateRowStatus": ""
}

### Uplink isolation table.
GET http://103.184.122.170/api/snmp/zxAnSecUplinkIsolationTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSecUplinkIsolationTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSecUplinkIsolateEnable": 2
}

