### Remote unit configuration file updating table.
GET http://103.184.122.170/api/snmp/zxAnRuConfigFileUpdateTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnRuConfigFileUpdateTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRuConfigFileUpdateOnuList": "",
    "zxAnRuConfigFileUpdateFileName": "",
    "zxAnRuConfigFileUpdateFileTypeId": 0,
    "zxAnRuConfigFileUpdateActiveMode": 1,
    "zxAnRuConfigFileUpdateFLocation": 1,
    "zxAnRuConfigFileUpdateStorageDId": 1,
    "zxAnRuConfigFileUpdateRowStatus": ""
}

### Remote unit configuration file updating status information table.<br/>Each item in this table records the updating result of remote unit<br/>configruation file last time.
GET http://103.184.122.170/api/snmp/zxAnRuCfUpdatingStatusTable
Authorization: Bearer {{token}}

