### The BFD Session Table describes the BFD sessions.
GET http://103.184.122.170/api/snmp/zxAnBfdSessTable
Authorization: Bearer {{token}}

### This table specifies BFD Session performance counters.
GET http://103.184.122.170/api/snmp/zxAnBfdSessPerfTable
Authorization: Bearer {{token}}

