### PON interface statistics table.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltIfCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltIfCurrPerfReset": ""
}

### The current 15 minutes performance data table of PON interface.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfCurr15MinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltIfCurr15MinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltIfC15MPerfReset": ""
}

### The minutes interval performance data table of PON OLT.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfCurrMinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltIfCurrMinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltIfCMinPerfReset": ""
}

### The current 1 day performance data table of PON interface.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltIfCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltIfC1DPerfReset": ""
}

### The 15 minutes interval performance data table of PON OLT.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfHis15MinPerfTable
Authorization: Bearer {{token}}

### The minutes interval history performance data table of PON OLT.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfHisMinPerfTable
Authorization: Bearer {{token}}

### The 1 day interval performance data table of PON OLT.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltIfHis1DayPerfTable
Authorization: Bearer {{token}}

### The performance alarm threshold profile<br/>list table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltPerfAlmPrfRowStatus": ""
}

### The performance alarm threshold profile table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltPerfRiseAlmThresh": "",
    "zxAnPonOltPerfRiseAlmClrThresh": "",
    "zxAnPonOltPerfRiseWarnThresh": "",
    "zxAnPonOltPerfRiseWarnClrThresh": "",
    "zxAnPonOltPerfFallWarnThresh": "",
    "zxAnPonOltPerfFallWarnClrThresh": "",
    "zxAnPonOltPerfFallAlmThresh": "",
    "zxAnPonOltPerfFallAlmClrThresh": "",
    "zxAnPonOltPerfThreshUsed": "",
    "zxAnPonOltPerfAlmConfRowStatus": ""
}

### The performance alarm threshold profile applying table of<br/>interfaces.<br/>The 'IfType' of ifIndex supports 1(physical interface)<br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfApplyTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOltPerfAlmPrfApplyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOltPerfAlmPrf": "",
    "zxAnPonOltAlmPrfApplyRowStatus": ""
}

### PON ONU interface statistics table
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuIfCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfCurrPerfReset": ""
}

### The current 15 minutes performance data table of PON ONU<br/>interface.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfCurr15MinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuIfCurr15MinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfC15MPerfReset": ""
}

### The minutes interval performance data table of PON ONU<br/>interface.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfCurrMinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuIfCurrMinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfCMinPerfReset": ""
}

### The current 1 day performance data table of PON ONU interface.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuIfCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfC1DPerfReset": ""
}

### The 15 minutes interval performance data table of PON ONU.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfHis15MinPerfTable
Authorization: Bearer {{token}}

### The minutes interval history performance data table of PON ONU.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfHisMinPerfTable
Authorization: Bearer {{token}}

### The 1 day interval performance data table of PON ONU.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfHis1DayPerfTable
Authorization: Bearer {{token}}

### The performance alarm threshold profile<br/>list table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuPerfAlmPrfRowStatus": ""
}

### The performance alarm threshold profile table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuPerfRiseAlmThresh": "",
    "zxAnPonOnuPerfRiseAlmClrThresh": "",
    "zxAnPonOnuPerfRiseWarnThresh": "",
    "zxAnPonOnuPerfRiseWarnClrThresh": "",
    "zxAnPonOnuPerfFallWarnThresh": "",
    "zxAnPonOnuPerfFallWarnClrThresh": "",
    "zxAnPonOnuPerfFallAlmThresh": "",
    "zxAnPonOnuPerfFallAlmClrThresh": "",
    "zxAnPonOnuPerfThreshUsed": "",
    "zxAnPonOnuPerfAlmConfRowStatus": ""
}

### The performance alarm threshold profile<br/>applying table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfApplyTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuPerfAlmPrfApplyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuPerfAlmPrf": "",
    "zxAnPonOnuAlmPrfApplyRowStatus": ""
}

