### PPPoE test interface configuration table.
GET http://103.184.122.170/api/snmp/zxAnPppoeTestIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPppoeTestIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPppoeTestIfUserVid": 0,
    "zxAnPppoeTestIfPppUserName": "",
    "zxAnPppoeTestIfPppPassword": "",
    "zxAnPppoeTestIfAuthMode": 1,
    "zxAnPppoeTestIfTimeout": 60,
    "zxAnPppoeTestIfUserMacAddress": "",
    "zxAnIfPppoeTestIfRowStatus": ""
}

### PPPoE test interface status table.
GET http://103.184.122.170/api/snmp/zxAnPppoeTestIfStatusTable
Authorization: Bearer {{token}}

