### The 15-minute interval performance data table of the optical<br/><br/>module.
GET http://103.184.122.170/api/snmp/zxAnOpticalCurr15MinPerfTable
Authorization: Bearer {{token}}

### The 1-day interval performance data table of the optical mudule.
GET http://103.184.122.170/api/snmp/zxAnOpticalCurr1DayPerfTable
Authorization: Bearer {{token}}

### The 15-minute interval historical performance data table of the<br/><br/>optical module.
GET http://103.184.122.170/api/snmp/zxAnOpticalHis15MinPerfTable
Authorization: Bearer {{token}}

### The 1-day interval historical performance data table of the optical<br/><br/>module.
GET http://103.184.122.170/api/snmp/zxAnOpticalHis1DayPerfTable
Authorization: Bearer {{token}}

### The minutes interval performance data table of the optical<br/><br/>module.
GET http://103.184.122.170/api/snmp/zxAnOpticalCurrMinPerfTable
Authorization: Bearer {{token}}

### The minutes interval historical performance data table of the<br/><br/>optical module.
GET http://103.184.122.170/api/snmp/zxAnOpticalHisMinPerfTable
Authorization: Bearer {{token}}

### The 15-minute interval performance data table of the optical<br/><br/>module channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanCurr15MinPerfTable
Authorization: Bearer {{token}}

### The 1-day interval performance data table of the optical module<br/><br/>channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanCurr1DayPerfTable
Authorization: Bearer {{token}}

### The 15-minute interval historical performance data table of the<br/><br/>optical module channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanHis15MinPerfTable
Authorization: Bearer {{token}}

### The 1-day interval historical performance data table of the<br/><br/>optical module channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanHis1DayPerfTable
Authorization: Bearer {{token}}

### The minutes interval performance data table of the optical<br/><br/>module channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanCurrMinPerfTable
Authorization: Bearer {{token}}

### The minutes interval historical performance data table of the<br/><br/>optical module channel.
GET http://103.184.122.170/api/snmp/zxAnOptChanHisMinPerfTable
Authorization: Bearer {{token}}

