### Virtual MAC address VLAN table.
GET http://103.184.122.170/api/snmp/zxAnVmacVlanTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacVlanTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacVlanTranslateMode": "",
    "zxAnVmacVlanRowStatus": ""
}

### Virtual MAC address interface configuration table.
GET http://103.184.122.170/api/snmp/zxAnVmacIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacIfConfTranslateEnable": 2,
    "zxAnVmacIfConfTranslateLimit": 16
}

### Interface virtual MAC address translation table.
GET http://103.184.122.170/api/snmp/zxAnVmacIfTranslateTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacIfTranslateTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacIfTranslateRowStatus": ""
}

### Interface reserved MAC address table.
GET http://103.184.122.170/api/snmp/zxAnVmacIfReservedMacTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacIfReservedMacTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacIfReservedRowStatus": ""
}

### Virtual MAC address profile table.
GET http://103.184.122.170/api/snmp/zxAnVmacProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacProfileRowStatus": ""
}

### Virtual MAC address profile item table.
GET http://103.184.122.170/api/snmp/zxAnVmacProfileItemTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVmacProfileItemTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVmacProfileItemAlgorithm": "",
    "zxAnVmacProfileItemCtrlByteValue": "",
    "zxAnVmacProfileItemCircuitIdType": "",
    "zxAnVmacProfileItemBitWidth": "",
    "zxAnVmacProfileItemRowStatus": ""
}

