### The MAC address assignment table of VRG card.
GET http://103.184.122.170/api/snmp/zxAnVrgCardMacAssignTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVrgCardMacAssignTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVrgCardBeginMacAddr": "",
    "zxAnVrgCardMacAddrTotalNum": 160000
}

### The binding relationship table between PON card and VRG card.
GET http://103.184.122.170/api/snmp/zxAnVrgCardBindTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVrgCardBindTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVrgCardBindPonCardReserveVid": "",
    "zxAnVrgCardBindVrgCardRack": "",
    "zxAnVrgCardBindVrgCardShelf": "",
    "zxAnVrgCardBindVrgCardSlot": "",
    "zxAnVrgCardBindRowStatus": ""
}

