### Automatic backup configuration table.
GET http://103.184.122.170/api/snmp/zxAnDataAutoBackupConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnDataAutoBackupConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDataAutoBackupEnable": 2,
    "zxAnDataAutoBackupStartTime": "",
    "zxAnDataAutoBackupInterval": 24,
    "zxAnDataAutoBackupHoldOffTime": 1,
    "zxAnDataAutoBackupMaxHoldOffTime": 24
}

### Automatic backup configuration table.
GET http://103.184.122.170/api/snmp/zxAnDataManualBackupConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnDataManualBackupConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDataManualBackupAction": ""
}

### Automatic backup status table.
GET http://103.184.122.170/api/snmp/zxAnDataBackupStatusTable
Authorization: Bearer {{token}}

