### A list of trap destination entries.
GET http://103.184.122.170/api/snmp/zxAnEventReceiverTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnEventReceiverTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEventReceiverIpAddrType": "",
    "zxAnEventReceiverIpAddr": "",
    "zxAnEventReceiverSnmpVer": 2,
    "zxAnEventReceiverCommunity": "",
    "zxAnEventReceiverUserName": "",
    "zxAnEventReceiverSecurityLevel": "",
    "zxAnEventReceiverEventFormat": 1,
    "zxAnEventReceiverEventType": "{ equipmentEvent,qualityOfServiceEvent,communicationsEvent,\r\nenvironmentEvent,processingErrorEvent",
    "zxAnEventReceiverMinEventLevel": 7,
    "zxAnEventReceiverEnable": 1,
    "zxAnEventReceiverIsZteNmsSever": "",
    "zxAnEventReceiverPort": 162,
    "zxAnEventRcvrTrapRptCompatible": 1,
    "zxAnEventReceiverRowStatus": ""
}

### Event definition table.
GET http://103.184.122.170/api/snmp/zxAnEventDefinitionTable
Authorization: Bearer {{token}}

### Event control profile table.
GET http://103.184.122.170/api/snmp/zxAnEventRptCtrlProfileTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnEventRptCtrlProfileTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEventRptCtrlPrfAdminStatus": 1,
    "zxAnEventRptCtrlPrfRowStatus": ""
}

### Event control profile rule table.
GET http://103.184.122.170/api/snmp/zxAnEventRptCtrlProfileRuleTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnEventRptCtrlProfileRuleTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEventRptCtrlEventCode": "",
    "zxAnEventRptCtrlProbableCause": "",
    "zxAnEventRptCtrlServiceAffect": "",
    "zxAnEventRptCtrlAdminStatus": "",
    "zxAnEventRptCtrlRptSeverity": "",
    "zxAnEventRptCtrlPrfRuleRowStatus": ""
}

### Event control profile table.
GET http://103.184.122.170/api/snmp/zxAnEventRptCtrlResourceTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnEventRptCtrlResourceTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEventRptCtrlResPrfName": "",
    "zxAnEventRptCtrlResAdminStatus": 5,
    "zxAnEventRptCtrlResRowStatus": ""
}

### A table of Active Alarms entries.
GET http://103.184.122.170/api/snmp/zxAnEventActiveTable
Authorization: Bearer {{token}}

### A table of variables to go with active alarm entries.
GET http://103.184.122.170/api/snmp/zxAnEventActiveVariableTable
Authorization: Bearer {{token}}

