### This table includes the enable or disable plug and play of<br/><br/>the rack.
GET http://103.184.122.170/api/snmp/zxAnRackTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnRackTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRackConfType": "",
    "zxAnRackInvSn": "",
    "zxAnRackRowStatus": ""
}

### This table includes the enable or disable plug and play of<br/><br/>the shelf.
GET http://103.184.122.170/api/snmp/zxAnShelfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnShelfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnShelfConfType": "",
    "zxAnShelfInvSn": "",
    "zxAnLogicShelfNo": "",
    "zxAnShelfRowStatus": ""
}

### This table includes the enable or disable plug and play of<br/><br/>the Card.
GET http://103.184.122.170/api/snmp/zxAnCardTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCardTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCardConfMainType": "",
    "zxAnCardAdminStatus": "",
    "zxAnCardCpuLoadThreshold": "",
    "zxAnCardMemUsageThreshold": "",
    "zxAnCardInvSn": "",
    "zxAnCardPowerSavingEnable": 2,
    "zxAnCardOperatorCode": "",
    "zxAnCardRowStatus": ""
}

### This table includes the enable or disable plug and play of<br/><br/>the subcard.
GET http://103.184.122.170/api/snmp/zxAnSubcardTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSubcardTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSubcardConfMainType": "",
    "zxAnSubcardAdminStatus": "",
    "zxAnSubcardInvSn": "",
    "zxAnSubcardRowStatus": ""
}

### This table includes the CPU information of the card.
GET http://103.184.122.170/api/snmp/zxAnCardCpuTable
Authorization: Bearer {{token}}

### This table includes file storage devices information.
GET http://103.184.122.170/api/snmp/zxAnStorageDeviceTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnStorageDeviceTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnStorageDeviceAccessEnable": ""
}

### The 5 minutes or 15 minutes interval performance data table of<br/><br/>card.
GET http://103.184.122.170/api/snmp/zxAnCardHisMinPerfTable
Authorization: Bearer {{token}}

