### This table contains ZESS domain information.
GET http://103.184.122.170/api/snmp/zxAnZessDomainTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnZessDomainTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnZessProtectMstpInstanceId": "",
    "zxAnZessPrimaryPort": "",
    "zxAnZessSecondaryPort": "",
    "zxAnZessPreupTime": 2,
    "zxAnZessDomainRevertiveMode": 1,
    "zxAnZessClearSwitchTimes": "",
    "zxAnZessDomainRowStatus": ""
}

