### A table of SNMPv1/v2c community string configuration.
GET http://103.184.122.170/api/snmp/zxAnSnmpCommunityConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSnmpCommunityConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSnmpCommunityConfPermission": 1,
    "zxAnSnmpCommunityConfRowStatus": ""
}

### A table of SNMPv1/v2c access-list name/number with ro/rw/all<br/><br/>option configuration.
GET http://103.184.122.170/api/snmp/zxAnSnmpAccesslistConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSnmpAccesslistConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSnmpAccesslistAclNumber": "",
    "zxAnSnmpAccesslistAclName": "",
    "zxAnSnmpAccesslistConfRowStatus": ""
}

