### A table that contains IPTV preview profiles.
GET http://localhost/api/snmp/zxAnIptvPrwProfileConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvPrwProfileConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvPrwMaxPrwTimes": 3,
    "zxAnIptvPrwMaxPrwDuration": 120,
    "zxAnIptvPrwBlackoutInterval": 60,
    "zxAnIptvPrwRecognizeTime": 20,
    "zxAnIptvPrwProfileRowStatus": ""
}

### A table that contains IPTV channels.
GET http://localhost/api/snmp/zxAnIptvChannelTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvChannelTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvChannelMVid": "",
    "zxAnIptvChannelGrpIpAddrType": 1,
    "zxAnIptvChannelGrpIpAddr": "",
    "zxAnIptvChannelSrcIpAddrType": 1,
    "zxAnIptvChannelSrcIpAddr": "FFFFFFF",
    "zxAnIptvChannelPrwProfile": "",
    "zxAnIptvChannelCdrEnable": 1,
    "zxAnIptvChannelRowStatus": ""
}

### A table that contains IPTV packages.
GET http://localhost/api/snmp/zxAnIptvPkgTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvPkgTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvPkgStartTime": 0,
    "zxAnIptvPkgEndTime": 0,
    "zxAnIptvPkgRowStatus": ""
}

### A table that contains list of channels in a package.
GET http://localhost/api/snmp/zxAnIptvPkgChannelTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvPkgChannelTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvPkgChannelAccessRight": 3,
    "zxAnIptvPkgChannelRowStatus": ""
}

### A table that contains IPTV information of a port.
GET http://localhost/api/snmp/zxAnIptvIfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvIfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvIfAccessCtrlEnable": 2,
    "zxAnIptvIfAccessCtrlMode": 2,
    "zxAnIptvIfAuthenticationEnable": 1
}

### A table that contains list of IPTV packages of a port.
GET http://localhost/api/snmp/zxAnIptvIfPkgTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvIfPkgTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvIfPkgRowStatus": ""
}

### A table that contains list of ports in a package.
GET http://localhost/api/snmp/zxAnIptvPkgPortListTable
Authorization: Bearer {{token}}

### A table that contains CDR servers.
GET http://localhost/api/snmp/zxAnIptvCdrServerTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIptvCdrServerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIptvCdrServerType": 1,
    "zxAnIptvCdrServerUserName": "",
    "zxAnIptvCdrServerPassWord": "",
    "zxAnMcastCdrServerFtpType": 1,
    "zxAnIptvCdrServerRowStatus": ""
}

