### Current statistics data table of service port.
GET http://103.184.122.170/api/snmp/zxAnSrvPortCurrStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSrvPortCurrStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSrvPortCurrStatsReset": "",
    "zxAnSrvPortCurrStatsRowStatus": ""
}

### The current minutes interval performance data table of the<br/><br/>service port.
GET http://103.184.122.170/api/snmp/zxAnSrvPortCurrMinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSrvPortCurrMinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSrvPortCMinReset": ""
}

### The current 1 day interval performance data table of the service<br/><br/>port.
GET http://103.184.122.170/api/snmp/zxAnSrvPortCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSrvPortCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSrvPortC1DReset": ""
}

### The historical minutes interval performance data table of the<br/><br/>service port.
GET http://103.184.122.170/api/snmp/zxAnSrvPortHisMinPerfTable
Authorization: Bearer {{token}}

### The historical 1 day interval performance data table of the<br/><br/>service port.
GET http://103.184.122.170/api/snmp/zxAnSrvPortHis1DayPerfTable
Authorization: Bearer {{token}}

### Enable/disable the service port performance.
GET http://103.184.122.170/api/snmp/zxAnSrvPortPerfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSrvPortPerfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSrvPortPerfConfRowStatus": ""
}

