### L3 interface ND proxy configuration table.
GET http://103.184.122.170/api/snmp/zxAnL3IfNdProxyConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnL3IfNdProxyConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnL3IfNdProxyConfEnable": 2
}

### This table provides ND configuration information on the L3<br/><br/>interface.<br/><br/>The interfaces for which this feature must be applicable are:<br/><br/>IfType = Physical Interface(1).
GET http://103.184.122.170/api/snmp/zxAnL3IfNdConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnL3IfNdConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnL3IfNdMngAddrConfFlagEnable": 2,
    "zxAnL3IfNdOtherConfFlagEnable": 2,
    "zxAnL3IfNdRaInterval": 0,
    "zxAnL3IfNdRaLifeTime": 0,
    "zxAnL3IfNdRaLinkMtu": 2,
    "zxAnL3IfNdReachableTime": 0,
    "zxAnL3IfNdRetransmitInterval": 0,
    "zxAnL3IfNdHopLimit": 0,
    "zxAnL3IfNdSuppressRaEnable": 1
}

### This table provides RA Prefix configuration information on the L3<br/><br/>interface.<br/><br/>The interfaces for which this feature must be applicable are:<br/><br/>IfType = Physical Interface(1).
GET http://103.184.122.170/api/snmp/zxAnL3IfNdRaPrefixConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnL3IfNdRaPrefixConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnL3IfNdRaPfxValidLifeTime": 0,
    "zxAnL3IfNdRaPfxPreferredLifeTime": 0,
    "zxAnL3IfNdRaPfxAutoConfEn": 1,
    "zxAnL3IfNdRaPfxOnLinkDetermineEn": 2,
    "zxAnL3IfNdRaPrefixConfRowStatus": ""
}

### This table provides static ND configuration and show ND items,<br/><br/>including dynamic ND item.<br/><br/><br/><br/>The interfaces for which this feature must be applicable are:<br/><br/>IfType = Physical Interface(1)
GET http://103.184.122.170/api/snmp/zxAnL3IfNdCacheTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnL3IfNdCacheTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnL3IfNdCacheMacAddress": "",
    "zxAnL3IfNdCacheRowStatus": ""
}

