### A table that contains the MAC move information.
GET http://localhost/api/snmp/zxAnMasMacMoveLogTable
Authorization: Bearer {{token}}

### MAC-anti-spoofing(Mas) trust configuration for permitting MAC<br/><br/>address moving based on interface table.
GET http://localhost/api/snmp/zxAnMasIfConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnMasIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnMasIfTrustEnable": 1
}

