### Domain name server table.
GET http://localhost/api/snmp/zxAnDnsDomainNameServerTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDnsDomainNameServerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDnsDomainNameSvrRowStatus": ""
}

### DNS IP domain table.
GET http://localhost/api/snmp/zxAnDnsIpDomainTable
Authorization: Bearer {{token}}

