### Tacacs+ server table.
GET http://103.184.122.170/api/snmp/zxAnTacacsPlusServerTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnTacacsPlusServerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnTacacsPlusServerKey": "",
    "zxAnTacacsPlusServerTimeout": 5,
    "zxAnTacacsPlusServerRowStatus": ""
}

### Tacacs+ server group table.
GET http://103.184.122.170/api/snmp/zxAnTacacsPlusServerGroupTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnTacacsPlusServerGroupTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnTacacsPlusServerGrpRowStatus": ""
}

