### LLDP Interface configuration table.
GET http://103.184.122.170/api/snmp/zxAnLldpIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLldpIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLldpIfConfMaxNeighbors": ""
}

