### IPv4 DHCP packets filtering based on VLAN table.
GET http://103.184.122.170/api/snmp/zxAnDhcpV4FilterVlanTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnDhcpV4FilterVlanTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDhcpV4FilterVlanRowStatus": ""
}

