### This table for configure ntp server.<br/><br/><br/><br/>Each entry is indexed by a zxAnNtpServerPriority.<br/><br/>To assign a ntp server, follow these steps:<br/><br/>1) Confirm the zxAnNtpServerPriority hasn`t be<br/><br/>used by other server.<br/><br/>2) Assign the server ip address zxAnNtpServerIpAddress,<br/><br/>this is mandory and this address must be also unique.<br/><br/>3) Configure ntp server version zxAnNtpServerVersion,<br/><br/>optional. Note that NE does not synchronize with<br/><br/>server which version is lower.<br/><br/>4) Assign a key to authe the server, optional.<br/><br/>Make sure this key must be exist and trusted,<br/><br/>otherwise NE will not authe the server.<br/><br/>5) Assign a server to be locked, optional.<br/><br/>If a server has been locked, then NE will only synchronize<br/><br/>with this server.
GET http://localhost/api/snmp/zxAnNtpServerTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNtpServerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNtpServerIpAddressType": 1,
    "zxAnNtpServerIpAddress": "",
    "zxAnNtpServerVersion": "",
    "zxAnNtpServerAuthKeyId": "",
    "zxAnNtpServerLock": "",
    "zxAnNtpServerRowStatus": ""
}

### NTP authentication configuration table.
GET http://localhost/api/snmp/zxAnNtpAuthTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNtpAuthTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNtpAuthKey": "",
    "zxAnNtpAuthTrust": "",
    "zxAnNtpAuthRowStatus": ""
}

### NTP layer 3 interface configuration table.
GET http://localhost/api/snmp/zxAnNtpIfConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNtpIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNtpIfBcastClientEnable": "",
    "zxAnNtpIfMcastClientEnable": "",
    "zxAnNtpIfMcastIpAddrType": 1,
    "zxAnNtpIfMcastIpAddress": "",
    "zxAnNtpIfBcastServerEnable": "",
    "zxAnNtpIfMcastServerEnable": "",
    "zxAnNtpIfMcastServerIpAddrType": 1,
    "zxAnNtpIfMcastServerIpAddress": "",
    "zxAnNtpIfConfigRowStatus": ""
}

### NTP peer table.
GET http://localhost/api/snmp/zxAnNtpPeerTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNtpPeerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNtpPeerVersion": "",
    "zxAnNtpPeerAuthKeyId": "",
    "zxAnNtpPeerRowStatus": ""
}

