### The table of watchdog function.
GET http://103.184.122.170/api/snmp/zxAnCardWatchdogTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCardWatchdogTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCardHardwareWatchdogEnable": 2,
    "zxAnCardTaskSuspendCardResetMode": 1,
    "zxAnCardSoftwareWatchdogEnable": 2,
    "zxAnCardTaskDurationThreshold": 5,
    "zxAnCardTaskCpuUsageThreshold": 75
}

