### The table containing infomation of LCT accessing<br/><br/>the network elements.
GET http://103.184.122.170/api/snmp/zxAnLctAccessTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLctAccessTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLctAccessDetailInfo": "",
    "zxAnLctAccessRowStatus": ""
}

