### PPPoE Intermediate Agent vlan switch table.<br/><br/>When PPPoE Intermediate Agent on the vlan is activated,<br/><br/>the related pppoe packets with this vlan will be processed.
GET http://103.184.122.170/api/snmp/zxAnPppoeIAVlanTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPppoeIAVlanTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPppoeIAVlanRowStatus": ""
}

### PPPoE Intermediate Agent interface configuration table
GET http://103.184.122.170/api/snmp/zxAnPppoeIAIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPppoeIAIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPppoeIAIfConfEnable": 2,
    "zxAnPppoeIAIfConfTrust": 2,
    "zxAnPppoeIAIfConfPolicy": 4
}

