### This table is for PTP configuration management.
GET http://103.184.122.170/api/snmp/zxAnPtpTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPtpTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPtpRack": 1,
    "zxAnPtpShelf": 1,
    "zxAnPtpSlot": "",
    "zxAnPtpFirstPtp": 1,
    "zxAnPtpClockType": 1,
    "zxAnPtpSlaveOnly": 1,
    "zxAnPtpDomainNumber": 0,
    "zxAnPtpProtocolType": "",
    "zxAnPtpProtocolIpAddrType": 1,
    "zxAnPtpProtocolIpAddress": "",
    "zxAnPtpProtocolMacAddress": "",
    "zxAnPtpEthWorkMode": 1,
    "zxAnPtpPacketsMode": 2,
    "zxAnPtpTwoStepFlag": 2,
    "zxAnPtpSendPacketsRate": 1,
    "zxAnPtpPhaseAdjust": 0,
    "zxAnPtpProtocolIpAddrPfxLen": 24,
    "zxAnPtpProtocolGatewayIpAddrType": 1,
    "zxAnPtpProtocolGatewayIpAddress": "0.0.0.0",
    "zxAnPtpRowStatus": ""
}

### This table includes PTP source configuration information<br/><br/>in NE equipment.
GET http://103.184.122.170/api/snmp/zxAnPtpRemoteSrcTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPtpRemoteSrcTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPtpRemoteSrcRack": "",
    "zxAnPtpRemoteSrcShelf": "",
    "zxAnPtpRemoteSrcSlot": "",
    "zxAnPtpRemoteSrcFirstMaster": "",
    "zxAnPtpRemoteSrcIpAddrType": 1,
    "zxAnPtpRemoteSrcIpAddress": "",
    "zxAnPtpRemoteSrcMacAddress": "",
    "zxAnPtpRemoteSrcDomainNumber": 0,
    "zxAnPtpRemoteSrcPathDelayAdjust": "",
    "zxAnPtpRemoteSrcPriority": 0,
    "zxAnPtpRemoteSrcRowStatus": ""
}

### The IEEE 1588 PTP server table.
GET http://103.184.122.170/api/snmp/zxAnPtpServerTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPtpServerTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPtpSvrEnable": 1,
    "zxAnPtpSvrPtpMsgProtocolType": 1,
    "zxAnPtpSvrPtpMsgTransmitChannel": 1,
    "zxAnPtpSvrSyncMsgInterval": 2,
    "zxAnPtpSvrDelayReqMsgInterval": 2,
    "zxAnPtpSvrPtpMsgVlan": 1,
    "zxAnPtpSvrRowStatus": ""
}

### The IEEE 1588 PTP client table.<br/><br/>It is the client of PTP server.
GET http://103.184.122.170/api/snmp/zxAnPtpClientTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPtpClientTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPtpClntRowStatus": ""
}

### The PTP Ethernet port configuration table.
GET http://103.184.122.170/api/snmp/zxAnPtpEthIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPtpEthIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPtpEthIfConfDlyCompensation": 0
}

### This table includes 1PPS source information in NE<br/><br/>equipment.
GET http://103.184.122.170/api/snmp/zxAnSyncTime1ppsSrcTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSyncTime1ppsSrcTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSyncTime1ppsSrcRack": "",
    "zxAnSyncTime1ppsSrcShelf": "",
    "zxAnSyncTime1ppsSrcSlot": "",
    "zxAnSyncTime1ppsSrcFirstPtp": 1,
    "zxAnSyncTime1ppsSrcSignalType": "",
    "zxAnSyncTime1ppsSrcPriority": "",
    "zxAnSyncTime1ppsSrcPortType": "",
    "zxAnSyncTime1ppsSrcPort": "",
    "zxAnSyncTime1ppsSrcDlyCompensate": 0,
    "zxAnSyncTime1ppsSrcRowStatus": ""
}

### This table includes TOD source information in NE<br/><br/>equipment.
GET http://103.184.122.170/api/snmp/zxAnSyncTimeTodSrcTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSyncTimeTodSrcTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSyncTimeTodSrcRack": "",
    "zxAnSyncTimeTodSrcShelf": "",
    "zxAnSyncTimeTodSrcSlot": "",
    "zxAnSyncTimeTodSrcPort": "",
    "zxAnSyncTimeTodSrcSignalType": "",
    "zxAnSyncTimeTodSrcYearAdjust": 0,
    "zxAnSyncTimeTodSrcRowStatus": ""
}

### This table includes 1PPS and TOD signal output ports<br/><br/>information in NE equipment.
GET http://103.184.122.170/api/snmp/zxAnSyncTimeOutputPortTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSyncTimeOutputPortTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSyncTimeOutputRack": "",
    "zxAnSyncTimeOutputShelf": "",
    "zxAnSyncTimeOutputSlot": "",
    "zxAnSyncTimeOutputPort": "",
    "zxAnSyncTimeOutputPortEnable": "",
    "zxAnSyncTimeOutputPortPhaseAdjus": 0,
    "zxAnSyncTimeOutputPortRowStatus": ""
}

