### EFM current performance table.
GET http://localhost/api/snmp/zxAnEfmCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnEfmCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEfmPerfReset": ""
}

### EFM current 15 minutes performance table.
GET http://localhost/api/snmp/zxAnEfmCurr15MinPerfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnEfmCurr15MinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEfmC15MPerfReset": ""
}

### EFM current 1 day performance table.
GET http://localhost/api/snmp/zxAnEfmCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnEfmCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnEfmC1DPerfReset": ""
}

### EFM history 15 minutes performance table.
GET http://localhost/api/snmp/zxAnEfmHis15MinPerfTable
Authorization: Bearer {{token}}

### EFM history 1 day performance table.
GET http://localhost/api/snmp/zxAnEfmHis1DayPerfTable
Authorization: Bearer {{token}}

