### DoS attack table.
GET http://103.184.122.170/api/snmp/zxAnSecDosAttackTable
Authorization: Bearer {{token}}

### CPU packet limit configuration table.
GET http://103.184.122.170/api/snmp/zxAnSecCpuPktLimitConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSecCpuPktLimitConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSecCpuPktLimitConfPktLmtEn": 1,
    "zxAnSecCpuPktLimitConfRateLimit": 256
}

### CPU packet limit statistic table.
GET http://103.184.122.170/api/snmp/zxAnSecCpuPktLimitStatsTable
Authorization: Bearer {{token}}

### CPU queue packet limit configuration table.
GET http://103.184.122.170/api/snmp/zxAnSecCpuQueuePktLmtConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnSecCpuQueuePktLmtConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSecCpuQueuePktLmtMaxRate": 256
}

### CPU queue packet limit configuration table.
GET http://103.184.122.170/api/snmp/zxAnSecCpuQueuePktLmtStatsTable
Authorization: Bearer {{token}}

