### This table includes the uplink interface loopback configuration<br/><br/>information.
GET http://localhost/api/snmp/zxAnIfLoopbackUplinkConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnIfLoopbackUplinkConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIfLoopbackUplinkEnable": 2,
    "zxAnIfLoopbackUplinkMode": "invalid",
    "zxAnIfLoopbackUplinkSVid": 0,
    "zxAnIfLoopbackUplinkCVid": 0
}

