### This table includes the general interface infomation.
GET http://103.184.122.170/api/snmp/zxAnIfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnIfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSubIfAlias": ""
}

