### Clearing ONU configuration data action table.
GET http://103.184.122.170/api/snmp/zxAnPonConfDataOnuClearTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonConfDataOnuClearTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonConfDataOnuClearAction": ""
}

### Configuration of PON data copy.
GET http://103.184.122.170/api/snmp/zxAnPonConfDataCopyTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonConfDataCopyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonConfDataCopyType": "",
    "zxAnPonConfDataCopySrcIfIndex": "",
    "zxAnPonConfDataCopyDestIfIndex": "",
    "zxAnPonConfDataCopyForceEnable": 1,
    "zxAnPonConfDataCopyRowStatus": ""
}

### Configuration of ONU type.
GET http://103.184.122.170/api/snmp/zxAnPonOnuTypeTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuTypeTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuTypePonType": "",
    "zxAnPonOnuTypeDesc": "",
    "zxAnPonOnuTypeAttr1": "",
    "zxAnPonOnuTypeAttr2": "",
    "zxAnPonOnuTypeAttr3": "",
    "zxAnPonOnuTypeAttr4": "",
    "zxAnPonOnuTypeAttr5": "",
    "zxAnPonOnuTypeAttr6": "",
    "zxAnPonOnuTypeAttr7": "",
    "zxAnPonOnuTypeAttr8": "",
    "zxAnPonOnuTypeAttr9": "",
    "zxAnPonOnuTypeAttr10": "",
    "zxAnPonOnuTypeRowStatus": ""
}

### Configuration of ONU interface attributes.
GET http://103.184.122.170/api/snmp/zxAnPonOnuIfAttrTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonOnuIfAttrTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfAttr1": "",
    "zxAnPonOnuIfAttr2": "",
    "zxAnPonOnuIfAttr3": "",
    "zxAnPonOnuIfAttr4": "",
    "zxAnPonOnuIfAttr5": "",
    "zxAnPonOnuIfAttr6": "",
    "zxAnPonOnuIfAttr7": "",
    "zxAnPonOnuIfAttr8": "",
    "zxAnPonOnuIfAttr9": "",
    "zxAnPonOnuIfAttr10": "",
    "zxAnPonOnuIfAttrRowStatus": ""
}

### This table is defined to control rogue ONU.
GET http://103.184.122.170/api/snmp/zxAnPonRogueOnuDetectInfoTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonRogueOnuDetectInfoTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRogueOnuDetectEnable": "",
    "zxAnRogueOnuLocatingEnable": "",
    "zxAnRogueOnuAutoCloseEnable": ""
}

### This table is defined to get rogue ONU information.
GET http://103.184.122.170/api/snmp/zxAnPonRogueOnuInfoTable
Authorization: Bearer {{token}}

### The PON port rogue ONU management table.<br/><br/>This table only is used for C600 serial.
GET http://103.184.122.170/api/snmp/zxAnPonPortRogueOnuConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonPortRogueOnuConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortRogueOnuLocatingEnable": "",
    "zxAnPortRogueOnuAutoCloseEnable": "",
    "zxAnPortRogueOnuDetectEnable": ""
}

### Received optical power on OLT side from ONU.
GET http://103.184.122.170/api/snmp/zxAnPonRxOpticalPowerTable
Authorization: Bearer {{token}}

### Received threshold of transceiver on OLT side.
GET http://103.184.122.170/api/snmp/zxAnPonRxOpticalPowerThreshTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonRxOpticalPowerThreshTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonRxPowerRisingAlarmThresh": -3000,
    "zxAnPonRxPowerFallingAlarmThresh": -34000,
    "zxAnPonRxPowerDetectPeriod": 900,
    "zxAnPonRxPowerRestoreDefault": ""
}

### Power levelling function.<br/><br/>OLT detect received optical power periodically,<br/><br/>then adjust the received optical power between the region.
GET http://103.184.122.170/api/snmp/zxAnPonPowerLevellingTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPonPowerLevellingTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonPowerLevellingEnable": 2,
    "zxAnPonPowerLevellingMinValue": -30000,
    "zxAnPonPowerLevellingMaxValue": -12000
}

