### This table contains information of the port identification format<br/><br/>profile configuration. One entry in this table reflects a format<br/><br/>profile defined by a manager.
GET http://103.184.122.170/api/snmp/zxAnPortIdFormatPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPortIdFormatPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortIdFormatPrfRowStatus": ""
}

### This table is to provide circuit ID syntax configuration. One entry<br/><br/>in this table reflects a syntax item define by a manager, which is<br/><br/>a component of a port identification format profile.
GET http://103.184.122.170/api/snmp/zxAnPortIdCircuitIdSyntaxTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPortIdCircuitIdSyntaxTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortIdCidComponentType": 1,
    "zxAnPortIdCidComponentId": "",
    "zxAnPortIdCidComponentWidth": 0,
    "zxAnPortIdCidComponentString": 0,
    "zxAnPortIdCidComponentProfile": 0,
    "zxAnPortIdCidComponentRowStatus": ""
}

### This table contains information of the port identification operator<br/><br/>profile configuration. One entry in this table reflects a operator<br/><br/>profile defined by a manager.
GET http://103.184.122.170/api/snmp/zxAnPortIdOperatorPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPortIdOperatorPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortIdOperAtmFormatPrf": "CHINA-TELECOM-DSL",
    "zxAnPortIdOperPtmEtherFormatPrf": "CHINA-TELECOM-DSL",
    "zxAnPortIdOperPonFormatPrf": "CHINA-TELECOM-PON",
    "zxAnPortIdOperLanFormatPrf": "CHINA-TELECOM-DSL",
    "zxAnPortIdOperDhcpV4L2RAEnable": 2,
    "zxAnPortIdOperDhcpV4L2RATrust": 2,
    "zxAnPortIdOperDhcpV4L2RAPolicy": 4,
    "zxAnPortIdOperDhcpV4AlcTag": "",
    "zxAnPortIdOperDhcpV6L2RAEnable": 2,
    "zxAnPortIdOperDhcpV6L2RATrust": 2,
    "zxAnPortIdOperDhcpV6L2RAPolicy": 4,
    "zxAnPortIdOperDhcpV6AlcTag": "",
    "zxAnPortIdOperPppoeIAEnable": 2,
    "zxAnPortIdOperPppoeIATrust": 2,
    "zxAnPortIdOperPppoeIAPolicy": 4,
    "zxAnPortIdOperPppoeAlcTag": "",
    "zxAnPortIdOperRelaySessionId": 65535,
    "zxAnPortIdOperPppMaxPayLoad": 2,
    "zxAnPortIdOperDslfIwfPppoe": 2,
    "zxAnPortIdOperDhcpV6L2RAWorkMode": 255,
    "zxAnPortIdOperDhcpV4RidEnable": 2,
    "zxAnPortIdOperDhcpV4RidFormatPrf": "",
    "zxAnPortIdOperDhcpV6RidEnable": 2,
    "zxAnPortIdOperDhcpV6RidFormatPrf": "",
    "zxAnPortIdOperPppoeRidEnable": 2,
    "zxAnPortIdOperPppoeRidFormatPrf": "",
    "zxAnPortIdOperPrfRowStatus": ""
}

### This table is to provide the VLAN operator profile configuration.<br/><br/>One entry in this table reflects an operator profile has been<br/><br/>applied to one VLAN.
GET http://103.184.122.170/api/snmp/zxAnPortIdVlanOperPrfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPortIdVlanOperPrfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortIdVlanOperPrf": "",
    "zxAnPortIdVlanOperPrfRowStatus": ""
}

### This table is to provide the interface operator profile<br/><br/>configuration. One entry in this table reflects an operator<br/><br/>profile has been applied to an interface.
GET http://103.184.122.170/api/snmp/zxAnPortIdIfOperPrfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnPortIdIfOperPrfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPortIdIfOperPrf": "",
    "zxAnPortIdIfOperPrfRowStatus": ""
}

