### The performance alarm threshold profile<br/><br/>list table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltPerfAlmPrfRowStatus": ""
}

### The performance alarm threshold profile table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfItemTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfItemTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltPerfRiseAlmThresh": "",
    "zxAnGponOltPerfRiseAlmClrThresh": "",
    "zxAnGponOltPerfRiseWarnThresh": "",
    "zxAnGponOltPerfRiseWarnClrThresh": "",
    "zxAnGponOltPerfFallWarnThresh": "",
    "zxAnGponOltPerfFallWarnClrThresh": "",
    "zxAnGponOltPerfFallAlmThresh": "",
    "zxAnGponOltPerfFallAlmClrThresh": "",
    "zxAnGponOltPerfThreshUsed": "",
    "zxAnGponOltPerfAlmItemRowStatus": ""
}

### The performance alarm threshold profile applying table of<br/><br/>interfaces.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfApplyTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOltPerfAlmPrfApplyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltPerfAlmPrf": "",
    "zxAnGponOltAlmPrfApplyRowStatus": ""
}

### The performance alarm threshold profile<br/><br/>list table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuPerfAlmPrfRowStatus": ""
}

### The performance alarm threshold profile table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfItemTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfItemTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuPerfRiseAlmThresh": "",
    "zxAnGponOnuPerfRiseAlmClrThresh": "",
    "zxAnGponOnuPerfRiseWarnThresh": "",
    "zxAnGponOnuPerfRiseWarnClrThresh": "",
    "zxAnGponOnuPerfFallWarnThresh": "",
    "zxAnGponOnuPerfFallWarnClrThresh": "",
    "zxAnGponOnuPerfFallAlmThresh": "",
    "zxAnGponOnuPerfFallAlmClrThresh": "",
    "zxAnGponOnuPerfThreshUsed": "",
    "zxAnGponOnuPerfAlmItemRowStatus": ""
}

### The performance alarm threshold profile<br/><br/>applying table of interfaces.
GET http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfApplyTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponOnuPerfAlmPrfApplyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuPerfAlmPrf": "",
    "zxAnGponOnuAlmPrfApplyRowStatus": ""
}

### Bandwidth allocation for one T-CONT in some ONU.<br/><br/>these bandwidths as following:<br/><br/>fixed bandwidth        ab. FBW<br/><br/>assured bandwidth      ab. ABW<br/><br/>non-assured bandwidth  ab. NABW<br/><br/>best effort bandwidth  ab. BEBW<br/><br/>additional bandwidth   ab. AddBW<br/><br/>guaranteed bandwidth   ab. GBW<br/><br/>maximum bandwidth      ab. MaxBW<br/><br/>minimum bandwidth      ab. MinBW<br/><br/>AddBW = NABW + BEBW<br/><br/>GBW   = FBW  + ABW<br/><br/>MaxBW = GBW  + AddBW<br/><br/>MinBW = FBW<br/><br/>NABW, BEBW, FBW and ABWare able to participate in DBA
GET http://103.184.122.170/api/snmp/zxAnGponSrvBandwidthPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvBandwidthPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvBwPrfFixed": "",
    "zxAnGponSrvBwPrfAssured": "",
    "zxAnGponSrvBwPrfMaximum": "",
    "zxAnGponSrvBwPrfType": "",
    "zxAnGponSrvBwPrfPriority": 0,
    "zxAnGponSrvBwPrfWeight": 0,
    "zxAnGponSrvBwPrfRowStatus": ""
}

### Rate configuration for one traffic as fowllowing:<br/><br/>sustainable information rate      ab. SIR<br/><br/>peak information rate             ab. PIR
GET http://103.184.122.170/api/snmp/zxAnGponSrvTrafficPrfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvTrafficPrfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTrafficPrfSir": "",
    "zxAnGponSrvTrafficPrfPir": "",
    "zxAnGponSvrTrafficPrfCbs": "",
    "zxAnGponSvrTrafficPrfPbs": "",
    "zxAnGponSrvTrafficPrfRowStatus": ""
}

### The PON port identifier configuration table.
GET http://103.184.122.170/api/snmp/zxAnGponSrvPonIdConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvPonIdConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvPonIdFormat": 1,
    "zxAnGponSrvPonId": ""
}

### The current performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltCurrReset": ""
}

### The current 15 minutes performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltCurr15MinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltCurr15MinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltC15MReset": ""
}

### The minutes interval performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltCurrMinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltCurrMinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltCMinReset": ""
}

### The current 1 day performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOltC1DReset": ""
}

### The 15 minutes interval performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltHis15MinPerfTable
Authorization: Bearer {{token}}

### The minutes interval history performance data table of GPON OLT.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltHisMinPerfTable
Authorization: Bearer {{token}}

### The 1 day interval performance data table of interfaces.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltHis1DayPerfTable
Authorization: Bearer {{token}}

### The configuration table of OLT PON interface.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel), only for zxAnGponSrvPonFecMode.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltPonIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltPonIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvPonName": "",
    "zxAnGponSrvPonAutoLearning": "",
    "zxAnGponSrvPonFecMode": "",
    "zxAnGponSrvPonScbPort": "",
    "zxAnGponSrvPonBerInterval": "",
    "zxAnGponSrvPonUncfgOnuAgingTime": "",
    "zxAnGponSrvRangeBase": "",
    "zxAnGponSrvRangeDiff": "",
    "zxAnGponSrvDiscoverPeriodNewOnu": "",
    "zxAnGponSrvDiscoverPeriodMissOnu": "",
    "zxAnGponSrvPonMcastEncryptEnable": "",
    "zxAnGponSrvResoureIdAssginMode": 1
}

### Table of PON port operation.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltOperTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOltOperTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvOltDeactiveAllOnu": "",
    "zxAnGponSrvOltEnableAllDeniedOnu": "",
    "zxAnGponSrvOltReset": "",
    "zxAnGponSrvOltDisableAllOnu": ""
}

### Table of unconfigured ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvUnConfOnuTable
Authorization: Bearer {{token}}

### Table of GPON service OLT QoS configuration.<br/><br/>The 'IfType' of ifIndex supports 1(physical interface)<br/><br/>and 5(PON channel).
GET http://103.184.122.170/api/snmp/zxAnGponSrvOltQosConfTable
Authorization: Bearer {{token}}

### The GPON ONU current performance data table
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuCurrReset": ""
}

### The current 15 minutes performance<br/><br/>data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurr15MinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurr15MinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuC15MReset": ""
}

### The minutes interval performance data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurrMinPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurrMinPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuCMinReset": ""
}

### The current 1 day performance data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurr1DayPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuCurr1DayPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuC1DReset": ""
}

### The 15 minutes interval performance data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuHis15MinPerfTable
Authorization: Bearer {{token}}

### The minutes interval history performance data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuHisMinPerfTable
Authorization: Bearer {{token}}

### The 1 day interval performance data table of GPON ONU.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuHis1DayPerfTable
Authorization: Bearer {{token}}

### The GPON GEM port current performance data table
GET http://103.184.122.170/api/snmp/zxAnGponSrvGemPortCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvGemPortCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponGemPortCurrReset": "",
    "zxAnGponGemPortCurrRowStatus": ""
}

### Enable/disable the GPON VPort interface statistics.
GET http://103.184.122.170/api/snmp/zxAnGponSrvVportCurrPerfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvVportCurrPerfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponVportCurrRowStatus": ""
}

### GPON card ONU authentication mode table.
GET http://103.184.122.170/api/snmp/zxAnGponSrvCardOnuAuthModeTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvCardOnuAuthModeTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvCardOnuAuthMode": 1
}

### The Table of ONU managment.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuMgmtTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuMgmtTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuMgmtTypeName": "",
    "zxAnGponOnuMgmtName": "",
    "zxAnGponOnuMgmtDesc": "",
    "zxAnGponOnuMgmtOpticalLineSn": "",
    "zxAnGponOnuMgmtRegMode": "",
    "zxAnGponOnuMgmtSn": "",
    "zxAnGponOnuMgmtPwd": "",
    "zxAnGponOnuMgmtLoid": "",
    "zxAnGponOnuMgmtRegistrationId": "",
    "zxAnGponOnuMgmtTargetStatus": 2,
    "zxAnGponOnuMgmtVportMode": 1,
    "zxAnGponOnuMgmtDbaMode": 1,
    "zxAnGponOnuMgmtOmccBwPrfName": "",
    "zxAnGponOnuMgmtEnableWithSn": 1,
    "zxAnGponOnuMgmtAuthPassCtrl": 0,
    "zxAnGponOnuMgmtUsFecEnable": 2,
    "zxAnGponOnuMgmtReonlineAuthInfo": 2,
    "zxAnGponOnuMgmtOmccEncryptEnable": 2,
    "zxAnGponOnuMgmtBerInterval": 5000,
    "zxAnGponOnuMgmtToDEnable": 2,
    "zxAnGponOnuMcastEncryptEnable": 2,
    "zxAnGponOnuMgmtPsk": 0,
    "zxAnGponOnuMgmtChannelId": 0,
    "zxAnGponOnuMgmtRowStatus": ""
}

### This table represents ONU's information of T-CONT.
GET http://103.184.122.170/api/snmp/zxAnGponSrvTcontTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvTcontTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTcontName": "",
    "zxAnGponSrvTcontBwPrfName": "",
    "zxAnGponSrvTcontAllocId": 256,
    "zxAnGponSrvTcontDbaGapMode": "",
    "zxAnGponSrvTcontRowStatus": ""
}

### This table represents the GEM port configuration.
GET http://103.184.122.170/api/snmp/zxAnGponSrvGemPortTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvGemPortTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvGemPortName": "",
    "zxAnGponSrvGemPortTcontIndex": "",
    "zxAnGponSrvGemPortPortId": 129,
    "zxAnGponSrvGemPortQueueOfTcont": 0,
    "zxAnGponSrvGemPortEnable": 1,
    "zxAnGponSrvGemPortDsQueueMapId": 0,
    "zxAnGponSrvGemPortUsQueueMapId": 0,
    "zxAnGponSrvGemPortEncrypt": 2,
    "zxAnGponSrvGemPortUsTrafficPrf": "",
    "zxAnGponSrvGemPortDsTrafficPrf": "",
    "zxAnGponSrvGemPortRowStatus": ""
}

### Table of the VPort.
GET http://103.184.122.170/api/snmp/zxAnGponSrvBpConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvBpConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvBpName": "",
    "zxAnGponSrvBpMapType": "",
    "zxAnGponSrvBpRowStatus": ""
}

### Table of the VPort map, it is used valid the<br/><br/>'zxAnGponSrvBpMapType' is not 'oneToOne'.
GET http://103.184.122.170/api/snmp/zxAnGponSrvBpMapConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvBpMapConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvBpMapConfRowStatus": ""
}

### Table of ONU status.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuStatusTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuStatusTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvOnuAdminStatus": ""
}

### Table of ONU command operation.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuOperTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnGponSrvOnuOperTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvOnuActivateAction": "",
    "zxAnGponSrvOnuUpdateSnAction": ""
}

### This table represents ONU distance.
GET http://103.184.122.170/api/snmp/zxAnGponSrvOnuDistanceTable
Authorization: Bearer {{token}}

