### An ATM loopback request table.
GET http://localhost/api/snmp/zxAnAtmPingTestTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnAtmPingTestTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnAtmPingTestInterface": "",
    "zxAnAtmPingTestVpi": "",
    "zxAnAtmPingTestVci": "",
    "zxAnAtmPingTestType": "",
    "zxAnAtmPingTestSentCells": "",
    "zxAnAtmPingTestRowStatus": ""
}

