### The statistic table based on S-VID and C-VID.
GET http://103.184.122.170/api/snmp/zxAnVlanCurrStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnVlanCurrStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVlanStatsReset": "",
    "zxAnVlanStatsRowStatus": ""
}

