### This table provides to configure DHCPv4 relay server groups.<br/><br/><br/><br/>When a relay server group is created in a device supporting this<br/><br/>table, a corresponding entry of this table will be added.<br/><br/><br/><br/>When a server group is destroyed in a device supporting this<br/><br/>table, a corresponding entry of this table will be deleted.
GET http://localhost/api/snmp/zxAnDrDhcpV4SvrGrpTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4SvrGrpTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4SvrGrpDesc": 0,
    "zxAnDrDhcpV4SvrGrpWorkMode": 2,
    "zxAnDrDhcpV4SvrMaxRetries": 10,
    "zxAnDrDhcpV4SvrUnavailableTime": 60,
    "zxAnDrDhcpV4SvrGrpRowStatus": ""
}

### This table provides to configure servers in the<br/><br/>DHCPv4 relay server groups.
GET http://localhost/api/snmp/zxAnDrDhcpV4SvrGrpSvrTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4SvrGrpSvrTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4SvrGrpSvrIpAddress": "",
    "zxAnDrDhcpV4SvrGrpSvrForwardMode": 1,
    "zxAnDrDhcpV4SvrGrpSvrCategory": 2,
    "zxAnDrDhcpV4SvrGrpSvrRowStatus": ""
}

### This table provides to configure<br/><br/>DHCPv4 relay server policy.<br/><br/><br/><br/>When a relay server policy is created in a device<br/><br/>supporting this table, a corresponding entry of this<br/><br/>table will be added.<br/><br/><br/><br/>When a server policy is destroyed in a device<br/><br/>supporting this table, a corresponding entry of<br/><br/>this table will be deleted.
GET http://localhost/api/snmp/zxAnDrDhcpV4SvrPolicyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4SvrPolicyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4SvrPolicySvrGrpId": 0,
    "zxAnDrDhcpV4SvrPolicyVClassId": 0,
    "zxAnDrDhcpV4SvrPolicyRowStatus": ""
}

### This table provides IP address allocation strategy<br/><br/>is to take the same service package equipment division<br/><br/>in a IP bundle.<br/><br/>It is the efficient use of IP resources.
GET http://localhost/api/snmp/zxAnDrDhcpV4IpBundleTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IpBundleTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IpBundleRowStatus": ""
}

### This table provides to configure attributes of<br/><br/>DHCPv4 relay server policy groups.
GET http://localhost/api/snmp/zxAnDrDhcpV4IpBundleIpAddrTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IpBundleIpAddrTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IpBundleIpCategory": "",
    "zxAnDrDhcpV4IpBundleIpRowStatus": ""
}

### This table provides the DHCPv4 relay server policy<br/><br/>for the equipment in an IP bundle.
GET http://localhost/api/snmp/zxAnDrDhcpV4IBSvrPolicyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IBSvrPolicyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IBSvrPolicyRowStatus": ""
}

### This table is to provide DHCP relay service apply to<br/><br/>L3 interface.
GET http://localhost/api/snmp/zxAnDrDhcpV4IfConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IfConfSvrPolicy": 2,
    "zxAnDrDhcpV4IfConfSvrGrpId": 0,
    "zxAnDrDhcpV4IfConfIpBundleEnable": 2,
    "zxAnDrDhcpV4IfConfAgentIpAddress": 0,
    "zxAnDrDhcpV4IfConfForwardSrcIp": 0
}

### This table provides the DHCPv4 relay agent policy for<br/><br/>L3 interface.
GET http://localhost/api/snmp/zxAnDrDhcpV4IfAgentPolicyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IfAgentPolicyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IfAgentPolicyAgentIp": "",
    "zxAnDrDhcpV4IfAgentRowStatus": ""
}

### This table provides the DHCPv4 relay<br/><br/>user information learnt by the interface<br/><br/>capable of this feature.<br/><br/><br/><br/>ifIndex is the L3 interface includes VLAN<br/><br/>and super VLAN.
GET http://localhost/api/snmp/zxAnDrDhcpV4UserViewTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4UserViewTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4UserViewRowStatus": ""
}

### DHCPv4 relay interface packet statistics table.
GET http://localhost/api/snmp/zxAnDrDhcpV4IfPktStatsTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV4IfPktStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV4IfPktStatsEnable": 1,
    "zxAnDrDhcpV4IfPktStatsReset": "",
    "zxAnDrDhcpV4IfPktStatsRowStatus": ""
}

### This table provides to configure DHCPv6 relay server groups.<br/><br/><br/><br/>When a relay server group is created in a device supporting this<br/><br/>table, a corresponding entry of this table will be added.<br/><br/><br/><br/>When a server group is destroyed in a device supporting this<br/><br/>table, a corresponding entry of this table will be deleted.
GET http://localhost/api/snmp/zxAnDrDhcpV6SvrGrpTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6SvrGrpTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6SvrGrpDesc": 0,
    "zxAnDrDhcpV6SvrGrpWorkMode": 2,
    "zxAnDrDhcpV6SvrMaxRetries": 10,
    "zxAnDrDhcpV6SvrUnavailableTime": 60,
    "zxAnDrDhcpV6SvrGrpRowStatus": ""
}

### This table provides to configure servers in the<br/><br/>DHCPv6 relay server groups.
GET http://localhost/api/snmp/zxAnDrDhcpV6SvrGrpSvrTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6SvrGrpSvrTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6SvrGrpSvrIpAddress": "",
    "zxAnDrDhcpV6SvrGrpSvrL3Interface": 0,
    "zxAnDrDhcpV6SvrGrpSvrCategory": 2,
    "zxAnDrDhcpV6SvrGrpSvrRowStatus": ""
}

### This table provides to configure<br/><br/>DHCPv6 relay server policy.<br/><br/><br/><br/>When a relay server policy is created in a device<br/><br/>supporting this table, a corresponding entry of this<br/><br/>table will be added.<br/><br/><br/><br/>When a server policy is destroyed in a device<br/><br/>supporting this table, a corresponding entry of<br/><br/>this table will be deleted.
GET http://localhost/api/snmp/zxAnDrDhcpV6SvrPolicyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6SvrPolicyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6SvrPolicyOptimalEn": 2,
    "zxAnDrDhcpV6SvrPolicyDftSvrGrpId": 0,
    "zxAnDrDhcpV6SvrPolicyRowStatus": ""
}

### This table provides to configure<br/><br/>DHCPv6 relay server VLAN policy.<br/><br/><br/><br/>When a relay server VLAN policy is created in a device<br/><br/>supporting this table, a corresponding entry of this<br/><br/>table will be added.<br/><br/><br/><br/>When a server VLAN policy is destroyed in a device<br/><br/>supporting this table, a corresponding entry of<br/><br/>this table will be deleted.
GET http://localhost/api/snmp/zxAnDrDhcpV6SvrVlanPolicyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6SvrVlanPolicyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6SvrVlanPolicySvrGrp": 0,
    "zxAnDrDhcpV6SvrVlanPolicyStatus": ""
}

### This table is to provide DHCPv6 relay service apply to<br/><br/>L3 interface.
GET http://localhost/api/snmp/zxAnDrDhcpV6IfConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6IfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6IfConfSvrPolicyName": 0,
    "zxAnDrDhcpV6IfConfAgentIpAddress": 0,
    "zxAnDrDhcpV6IfConfSvrIpAddress": 0,
    "zxAnDrDhcpV6IfConfSvrL3Interface": 0
}

### This table provides the DHCPv6 relay<br/><br/>user information learnt by the interface<br/><br/>capable of this feature.<br/><br/><br/><br/>ifIndex is the L3 interface includes VLAN<br/><br/>and super VLAN.
GET http://localhost/api/snmp/zxAnDrDhcpV6UserViewTable
Authorization: Bearer {{token}}

### DHCPv6 relay interface packet statistics table.
GET http://localhost/api/snmp/zxAnDrDhcpV6IfPktStatsTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnDrDhcpV6IfPktStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnDrDhcpV6IfPktStatsEnable": 1,
    "zxAnDrDhcpV6IfPktStatsReset": "",
    "zxAnDrDhcpV6IfPktStatsRowStatus": ""
}

