### Log configuration table.
GET http://103.184.122.170/api/snmp/zxAnLogConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLogConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLogEnable": 1
}

