### NG-PON2 group table.
GET http://localhost/api/snmp/zxAnNgpon2GroupTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNgpon2GroupTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNgpon2GroupIfs": "",
    "zxAnNgpon2GroupRowStatus": ""
}

### The NG-PON2 ONU configuration table.
GET http://localhost/api/snmp/zxAnNgpon2OnuConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNgpon2OnuConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNgpon2OnuProtectionChannels": ""
}

### The NG-PON2 ONU status table.
GET http://localhost/api/snmp/zxAnNgpon2OnuStatusTable
Authorization: Bearer {{token}}

### The NG-PON2 ONU action table.
GET http://localhost/api/snmp/zxAnNgpon2OnuActionTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnNgpon2OnuActionTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnNgpon2OnuAction": ""
}

