### CES port table.
GET http://103.184.122.170/api/snmp/zxAnCesIfTable
Authorization: Bearer {{token}}

### CES port extension table.
GET http://103.184.122.170/api/snmp/zxAnCesIfExtTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCesIfExtTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCesIfExtMacAddress": "",
    "zxAnCesIfExtIpAddressType": 1,
    "zxAnCesIfExtIpAddress": ""
}

### CES pseudo-wire table.
GET http://103.184.122.170/api/snmp/zxAnCesPwTable
Authorization: Bearer {{token}}

### CES MEF8 pseudo-wire table.
GET http://103.184.122.170/api/snmp/zxAnCesMef8PwTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCesMef8PwTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCesMef8PwName": "",
    "zxAnCesMef8PwVlanId": "",
    "zxAnCesMef8PwPriority": 7,
    "zxAnCesMef8PwDestMac": "",
    "zxAnCesMef8PwOutboundLabel": "",
    "zxAnCesMef8PwInboundLabel": "",
    "zxAnCesMef8PwPayloadSize": 8,
    "zxAnCesMef8PwJitterBufferSize": "",
    "zxAnCesMef8PwRtpUsed": 1,
    "zxPwCesMef8PwRtpSsrc": "",
    "zxAnCesMef8PwRowStatus": ""
}

### CES TDM Service table.
GET http://103.184.122.170/api/snmp/zxAnCesTdmServiceTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCesTdmServiceTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCesTdmServicePwType": 1,
    "zxAnCesTdmServicePwId": "",
    "zxAnCesTdmServiceRowStatus": ""
}

### CES TDM protection table.
GET http://103.184.122.170/api/snmp/zxAnCesTdmProtectTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnCesTdmProtectTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnCesTdmProtectSlavePort": "",
    "zxAnCesTdmProtectAction": "",
    "zxAnCesTdmProtectRowStatus": ""
}

