### IS-IS circuit configuration table.
GET http://103.184.122.170/api/snmp/zxAnIsisCircuitConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnIsisCircuitConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIsisCircuitConfAdminStatus": "",
    "zxAnIsisCircuitConfLevel": 3,
    "zxAnIsisCircuitConfBfdSupport": 2,
    "zxAnIsisCircuitConfRowStatus": ""
}

### IS-IS authentication table.
GET http://103.184.122.170/api/snmp/zxAnIsisAuthenticationTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnIsisAuthenticationTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIsisAuthType": 1,
    "zxAnIsisAuthPlainPassword": "",
    "zxAnIsisAuthMd5Password": ""
}

### IS-IS redistribution configuration table.
GET http://103.184.122.170/api/snmp/zxAnIsisRedistributeTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnIsisRedistributeTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnIsisRedistributeLevel": 2,
    "zxAnIsisRedistributeMetricType": 1,
    "zxAnIsisRedistributeMetric": "",
    "zxAnIsisRedistributeRowStatus": ""
}

