### An ATM loopback request table.
GET http://103.184.122.170/api/snmp/zxAnAtmPingTestTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnAtmPingTestTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnAtmPingTestInterface": "",
    "zxAnAtmPingTestVpi": "",
    "zxAnAtmPingTestVci": "",
    "zxAnAtmPingTestType": "",
    "zxAnAtmPingTestSentCells": "",
    "zxAnAtmPingTestRowStatus": ""
}

