### This table includes the license file information.
GET http://103.184.122.170/api/snmp/zxAnLicenseFileTable
Authorization: Bearer {{token}}

### This table includes license feature information.
GET http://103.184.122.170/api/snmp/zxAnLicenseFeatureTable
Authorization: Bearer {{token}}

### This table includes the running license feature information.
GET http://103.184.122.170/api/snmp/zxAnLicenseRunningFeatureTable
Authorization: Bearer {{token}}

