### Multicast group traffic table.
GET http://103.184.122.170/api/snmp/zxAnMcastGrpTrafficTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnMcastGrpTrafficTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnMCastGrpTrafficRowStatus": ""
}

