### This table is to provide aggregator configuration, and<br/><br/>contains information about every aggregator in this system.<br/><br/>An aggregator is associated with a link aggregation group,<br/><br/>which named smartgroup.
GET http://103.184.122.170/api/snmp/zxAnLacpAggTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLacpAggTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLacpAggActorSysPriority": 32768,
    "zxAnLacpAggMode": 1,
    "zxAnLacpAggLoadBalanceMode": 4,
    "zxAnLacpAggActorAdminKey": "",
    "zxAnLacpAggRowStatus": ""
}

### This table is to provide aggregation port configuration, and<br/><br/>contains information about every aggregation port associated<br/><br/>with this device. A row appears in this table for each<br/><br/>physical port as a member port of the smartgroup.
GET http://103.184.122.170/api/snmp/zxAnLacpAggPortTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLacpAggPortTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLacpAggId": "",
    "zxAnLacpAggPortMode": "",
    "zxAnLacpAggPortTimeOut": 1,
    "zxAnLacpAggPortPriority": 32768,
    "zxAnLacpAggPortSubgroupId": 0,
    "zxAnLacpAggPortProtectionMode": 1,
    "zxAnLacpAggPortRowStatus": ""
}

### A table that contains Link Aggregation Protocol statistics<br/><br/>about every port that is associated with this device. A row<br/><br/>appears in this table for each aggregation port.
GET http://103.184.122.170/api/snmp/zxAnLacpAggPortStatsTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLacpAggPortStatsTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLacpAggPortStatsReset": ""
}

