### Remote unit access control rule table.
GET http://103.184.122.170/api/snmp/zxAnRuAccessCtrlRuleTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnRuAccessCtrlRuleTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRuAccessCtrlRuleSerialNumber": "",
    "zxAnRuAccessCtrlRuleVendorId": "",
    "zxAnRuAccessCtrlRuleFirmware": "",
    "zxAnRuAccessCtrlRuleRowStatus": ""
}

### Remote unit access control inventory table.
GET http://103.184.122.170/api/snmp/zxAnRuAccessCtrlInventoryTable
Authorization: Bearer {{token}}

