### Remote unit access control rule table.
GET http://localhost/api/snmp/zxAnRuAccessCtrlRuleTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxAnRuAccessCtrlRuleTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnRuAccessCtrlRuleSerialNumber": "",
    "zxAnRuAccessCtrlRuleVendorId": "",
    "zxAnRuAccessCtrlRuleFirmware": "",
    "zxAnRuAccessCtrlRuleRowStatus": ""
}

### Remote unit access control inventory table.
GET http://localhost/api/snmp/zxAnRuAccessCtrlInventoryTable
Authorization: Bearer {{token}}

