### This table represents the interface loopback detection<br/><br/>configuration.
GET http://103.184.122.170/api/snmp/zxAnLoopbackDetectIfConfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLoopbackDetectIfConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLoopbackDetectIfEnable": "",
    "zxAnLoopbackDetectIfActiveEnable": "",
    "zxAnLoopbackDetectIfStartVid": 65535,
    "zxAnLoopbackDetectIfEndVid": 65535,
    "zxAnLoopbackDetectIfConfMode": 1
}

### This table represents the loopbacked interfaces.
GET http://103.184.122.170/api/snmp/zxAnLoopbackDetectIfStatusTable
Authorization: Bearer {{token}}

### This table provides the parameters to start an interface manual<br/><br/>loopback detection.<br/><br/>The parameters cann't be read after starting the detection.
GET http://103.184.122.170/api/snmp/zxAnLoopbackManualDetectIfTable
Authorization: Bearer {{token}}

###
POST http://103.184.122.170/api/snmp/zxAnLoopbackManualDetectIfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnLoopbackManualDetectIfAction": "",
    "zxAnLoopbackManualDetectIfVid": 65535,
    "zxAnLoopbackManualDetectIfPkts": 3
}

