### Virtual network device configuration table.
GET http://localhost/api/snmp/zxr10VndConfTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10VndConfTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10VndConfAssignMode": 1,
    "zxr10VndConfDescription": "",
    "zxr10VndConfStartAction": "",
    "zxr10VndConfRowStatus": ""
}

### Virtual network device MPU deployment table.
GET http://localhost/api/snmp/zxr10VndDeployMpuTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10VndDeployMpuTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10VndDeployMpuRowStatus": ""
}

### Virtual network device interface assignment table.
GET http://localhost/api/snmp/zxr10VndAssignInterfaceTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10VndAssignInterfaceTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10VndAssignInterfaceMode": "",
    "zxr10VndAssignInterfaceRowStatus": ""
}

### Virtual network device interface configuration table.
GET http://localhost/api/snmp/zxr10VndInterfaceConfTable
Authorization: Bearer {{token}}

### Virtual network device card assignment table.
GET http://localhost/api/snmp/zxr10VndAssignCardTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10VndAssignCardTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10VndAssignCardRowStatus": ""
}

### Virtual network device card configuration table.
GET http://localhost/api/snmp/zxr10VndCardConfTable
Authorization: Bearer {{token}}

