### The fan system table.
GET http://localhost/api/snmp/zxr10FanSystemTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10FanSystemTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10FanSysSpeedAdjustStrategy": 1
}

### The system cpu load threshold table.
GET http://localhost/api/snmp/zxr10SystemCpuLoadThreshTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10SystemCpuLoadThreshTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10SystemCpuLoadThreshold": "",
    "zxr10SystemCpuLoadThreshRowStaus": ""
}

### The system memory usage threshold table.
GET http://localhost/api/snmp/zxr10SystemMemUsageThreshTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10SystemMemUsageThreshTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10SysMemUsageThreshold": "",
    "zxr10SysMemUsageThreshRowStaus": ""
}

### The card power supply table.
GET http://localhost/api/snmp/zxr10CardPowerSupplyTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10CardPowerSupplyTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10CardPowerSupplyOperation": ""
}

### the description of Cpusystem information<br/><br/>in the zxr10 card .<br/><br/>it is a list of Cpusystem entries.
GET http://localhost/api/snmp/zxr10CpusystemTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10CpusystemTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10SystemCardCpuLoadThreshold": 0,
    "zxr10SystemCardMemUsageThreshold": 0
}

### The description of fan module information.
GET http://localhost/api/snmp/zxr10FanTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10FanTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10FanRatio": ""
}

### the description of ShelfTemperature information.
GET http://localhost/api/snmp/zxr10ShelfTemperatureTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10ShelfTemperatureTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10EnvironTemperatureLowThreshold": "",
    "zxr10EnvironTemperatureHighThreshold1": 55,
    "zxr10EnvironTemperatureHighThreshold2": 70,
    "zxr10EnvTempOverheatProtectEn": 1
}

### the description of BoardTemperature information.
GET http://localhost/api/snmp/zxr10BoardTempTable
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/zxr10BoardTempTable/:id
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxr10BoardTempMajorThreshold": 108
}

### the description of power information.
GET http://localhost/api/snmp/zxr10PowerInfoTable
Authorization: Bearer {{token}}

### the description of power module.
GET http://localhost/api/snmp/zxr10PowerModuleTable
Authorization: Bearer {{token}}

### the description of power division.
GET http://localhost/api/snmp/zxr10PowerDivisionTable
Authorization: Bearer {{token}}

### The description of board power information.
GET http://localhost/api/snmp/zxr10BoardPowerTable
Authorization: Bearer {{token}}

