### Configure Aggregating Port parameters.
GET http://localhost/api/snmp/lacpAggregatingTable
Authorization: Bearer {{token}}

### Aggregating port bound aggregated port.
GET http://localhost/api/snmp/lacpAggBoundTable
Authorization: Bearer {{token}}

### Configure Aggregating Port mclag parameters.
GET http://localhost/api/snmp/zxr10LacpAggMclagTable
Authorization: Bearer {{token}}

### Configure Aggregated Port parameters.
GET http://localhost/api/snmp/lacpAggregatedTable
Authorization: Bearer {{token}}

