### Login
POST http://103.184.122.170/api/cacti/login
Content-Type: application/json

{
    "action": "login",
    "login_username": "wijaya",
    "login_password": "wijaya@2024"
}

### Logout
GET http://103.184.122.170/api/cacti/logout






### Tree
GET http://103.184.122.170/api/cacti/graph_view
?action=get_node
&tree_id=0
&id=%23

### Tree > Node
GET http://103.184.122.170/api/cacti/graph_view
?action=get_node
&tree_id=0
&id=tree_anchor-2

### Graph Filters 
GET http://103.184.122.170/api/cacti/graph_view
?action=tree_content
&node=tbranch-15
&tree_id=2
&leaf_id=15
&hgd=
&header=false
&page=1






### Content
GET http://103.184.122.170/api/cacti/graph_json
?rra_id=0
&local_graph_id=457
&graph_start=2025-01-31
&graph_end=2025-02-01
&graph_height=200
&graph_width=700

### Graph Utility View
GET http://103.184.122.170/api/cacti/graph_json
?rra_id=1
&local_graph_id=457
&graph_start=2025-01-31
&graph_end=2025-02-01
&graph_height=200
&graph_width=700
&disable_cache=true

### Summary Details
GET http://103.184.122.170/api/cacti/graph_xport
?local_graph_id=457
&rra_id=0
&format=table
&graph_start=2025-01-31
&graph_end=2025-02-01

