
###
GET http://localhost/api/main

###
POST http://localhost/api/main
Content-Type: application/json

{
    "user":"name",
    "pass":"word"
}

###
POST http://localhost/api/main
Content-Type: application/x-www-form-urlencoded

user=name&pass=word