

### https://www.tembolok.id/setting-olt-zte-c320-netnumen/#google_vignette

### NE Protocol Manager > VLAN > Static VLAN
GET http://localhost/api/snmp/zxAnVlanTable
Authorization: Bearer {{token}}

### NE Protocol Manager > VLAN > Static VLAN > New
POST http://localhost/api/snmp/zxAnVlanTable/100
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVlanName": "VLAN0100",
    "zxAnVlanDesc": "VLAN0100",
    "zxAnVlanRowStatus": 4
}

### NE Protocol Manager > VLAN > Static VLAN > Delete
POST http://localhost/api/snmp/zxAnVlanTable/100
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVlanRowStatus": 6
}


# 285278721.268501248

# 285278721.1
# 285278721.2




### 
GET http://localhost/api/snmp/ifIndex
Authorization: Bearer {{token}}

### NE Protocol Manager > VLAN > Port VLAN
GET http://localhost/api/snmp/zxAnVlanIfConfTable
Authorization: Bearer {{token}}

### NE Protocol Manager > VLAN > Port VLAN > VLAN Bind
POST http://localhost/api/snmp/zxAnVlanIfConfVlanCmdTable/285279235.0
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnVlanIfConfVlanCmd": 1,
    "zxAnVlanIfConfVlanList": "100"
}






### Profile Configuration > GPON > Bandwidth > ONU Bandwidth Profile
GET http://localhost/api/snmp/zxAnGponSrvBandwidthPrfTable
Authorization: Bearer {{token}}

### Profile Configuration > GPON > Bandwidth > ONU Bandwidth Profile > New
POST http://localhost/api/snmp/zxAnGponSrvBandwidthPrfTable/4.49.48.48.77
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvBwPrfFixed": 100000,
    "zxAnGponSrvBwPrfType": 1,
    "zxAnGponSrvBwPrfRowStatus": 4
}

### Profile Configuration > GPON > Bandwidth > ONU Bandwidth Profile > Delete
POST http://localhost/api/snmp/zxAnGponSrvBandwidthPrfTable/4.49.48.48.77
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvBwPrfRowStatus": 6
}






### Profile Configuration > GPON > Bandwidth > Traffic Profile
GET http://localhost/api/snmp/zxAnGponSrvTrafficPrfTable
Authorization: Bearer {{token}}

### Profile Configuration > GPON > Bandwidth > Traffic Profile > New
POST http://localhost/api/snmp/zxAnGponSrvTrafficPrfTable/4.116.101.115.116
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTrafficPrfSir": 0,
    "zxAnGponSrvTrafficPrfPir": 64,
    "zxAnGponSvrTrafficPrfCbs": 0,
    "zxAnGponSvrTrafficPrfPbs": 0,
    "zxAnGponSrvTrafficPrfRowStatus": 4
}

### Profile Configuration > GPON > Bandwidth > Traffic Profile > Delete
POST http://localhost/api/snmp/zxAnGponSrvTrafficPrfTable/4.116.101.115.116
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTrafficPrfRowStatus": 6
}






### Profile Configuration > GPON > VOIP > VLAN Profile
GET http://localhost/api/snmp/zxAnGponRmVlanPrfTable
Authorization: Bearer {{token}}

### Profile Configuration > GPON > VOIP > VLAN Profile > New
POST http://localhost/api/snmp/zxAnGponRmVlanPrfTable/8.80.82.79.70.73.76.69.49
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponRmVlanPrfTagMode": 1,
    "zxAnGponRmVlanPrfCVid": 100,
    "zxAnGponRmVlanPrfCtagCos": 7,
    "zxAnGponRmVlanPrfRowStatus": 4
}

### Profile Configuration > GPON > VOIP > VLAN Profile > Delete
POST http://localhost/api/snmp/zxAnGponRmVlanPrfTable/8.80.82.79.70.73.76.69.49
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponRmVlanPrfRowStatus": 6
}







### Profile Configuration > Global > ONU Type Profile
GET http://localhost/api/snmp/zxAnPonOnuTypeTable
Authorization: Bearer {{token}}

###
GET http://localhost/api/snmp/zxAnPonOnuIfAttrTable
Authorization: Bearer {{token}}

### Profile Configuration > Global > ONU Type Profile > New
POST http://localhost/api/snmp/zxAnPonOnuTypeTable/6.65.66.67.88.89.90
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuTypePonType": 2,
    "zxAnPonOnuTypeDesc": "ABCXYZ",
    "zxAnPonOnuTypeAttr1": 255,
    "zxAnPonOnuTypeAttr2": 255,
    "zxAnPonOnuTypeAttr3": 255,
    "zxAnPonOnuTypeAttr4": 255,
    "zxAnPonOnuTypeAttr5": 2,
    "zxAnPonOnuTypeAttr6": 7,
    "zxAnPonOnuTypeAttr9": 0,
    "zxAnPonOnuTypeAttr8": 0,
    "zxAnPonOnuTypeRowStatus": 4
}

###
POST http://localhost/api/snmp/zxAnPonOnuIfAttrTable/6.65.66.67.88.89.90.655460
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuIfAttrRowStatus": 4
}

### Profile Configuration > Global > ONU Type Profile > Delete
POST http://localhost/api/snmp/zxAnPonOnuTypeTable/6.65.66.67.88.89.90
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnPonOnuTypeRowStatus": 6
}






### ONU Manager
GET http://localhost/api/snmp/zxAnGponSrvOltPonIfConfTable
Authorization: Bearer {{token}}

### ONU Manager > Unauthenticated ONU Configuration > Refresh
GET http://localhost/api/snmp/zxAnGponSrvUnConfOnuTable
Authorization: Bearer {{token}}

###
GET http://localhost/api/snmp/zxAnGponSrvOnuMgmtTable
Authorization: Bearer {{token}}

### ONU Manager > Unauthenticated ONU Configuration > Add To
### ONU Manager > New
POST http://localhost/api/snmp/zxAnGponSrvOnuMgmtTable/285278721.3
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponOnuMgmtRegMode": 1,
    "zxAnGponOnuMgmtSn": "ZTEGC915E414",
    "zxAnGponOnuMgmtName": "ZTE-F660V8.0",
    "zxAnGponOnuMgmtTypeName": "ZTE-F622",
    "zxAnGponOnuMgmtDesc": "",
    "zxAnGponOnuMgmtTargetStatus": 2,
    "zxAnGponOnuMgmtVportMode": 1,
    "zxAnGponOnuMgmtRowStatus": 4
}

### ONU Manager > Delete
POST http://localhost/api/snmp/zxAnGponSrvOnuMgmtTable/285278721.3
Authorization: Bearer {{token}}
Content-Type: application/json

{
    
    "zxAnGponOnuMgmtRowStatus": 6
}





### ONU Manager > Line Configurations > T-CONT Configuration > New
GET http://localhost/api/snmp/zxAnGponSrvTcontTable/
Authorization: Bearer {{token}}

### ONU Manager > Line Configurations > T-CONT Configuration > New
POST http://localhost/api/snmp/zxAnGponSrvTcontTable/285278721.1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTcontName": "T1",
    "zxAnGponSrvTcontBwPrfName": "100M",
    "zxAnGponSrvTcontRowStatus": 4
}

###
POST http://localhost/api/snmp/zxAnGponSrvTcontTable/285278721.1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvTcontName": "T1",
    "zxAnGponSrvTcontBwPrfName": "100M",
    "zxAnGponSrvTcontDbaGapMode": 1
}






### ONU Manager > Line Configurations > GEM Port Configuration > New
GET http://localhost/api/snmp/zxAnGponSrvGemPortTable/
Authorization: Bearer {{token}}

### ONU Manager > Line Configurations > GEM Port Configuration > New
POST http://localhost/api/snmp/zxAnGponSrvGemPortTable/285278721.1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponSrvGemPortName": "G1",
    "zxAnGponSrvGemPortTcontIndex": 1,
    "zxAnGponSrvGemPortQueueOfTcont": 0,
    "zxAnGponSrvGemPortEnable": 1,
    "zxAnGponSrvGemPortUsTrafficPrf": "50M",
    "zxAnGponSrvGemPortDsTrafficPrf": "50M",
    "zxAnGponSrvGemPortEncrypt": 2,
    "zxAnGponSrvGemPortRowStatus": 4
}






### ONU Manager > VPort Service Configurations > Service Port > New
GET http://localhost/api/snmp/zxAnSrvPortConfTable/
Authorization: Bearer {{token}}

### ONU Manager > VPort Service Configurations > Service Port > New
POST http://localhost/api/snmp/zxAnSrvPortConfTable/285278721.402718976
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnSrvPortServiceMode": 4,
    "zxAnSrvPortUserVid": 100,
    "zxAnSrvPortCVid": 100,
    "zxAnSrvPortBrgIfId": 1,
    "zxAnSrvPortDesc": "",
    "zxAnSrvPortAdminStatus": 1,
    "zxAnSrvPortCtagCos": 255,
    "zxAnSrvPortSVid": 0,
    "zxAnSrvPortStagCos": 255,
    "zxAnSrvPortQueueId": 255,
    "zxAnSrvPortRowStatus": 4
}






### ONU Manager > PON Service Configurations > ONU Service
GET http://localhost/api/snmp/zxAnGponRmServiceMapTable
Authorization: Bearer {{token}}

### ONU Manager > PON Service Configurations > ONU Service > New
POST http://localhost/api/snmp/zxAnGponRmServiceMapTable/285278721.402718976
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponRmServiceGemPort": 1,
    "zxAnGponRmServiceMapType": 2,
    "zxAnGponRmServiceMapVid": "006400000000000000000000000000000000000000000000",
    "zxAnGponRmServiceRowStatus": 4
}






### ONU Manager > WAN Service Configurations > ONU Service WAN IP Configuration > New
GET  http://localhost/api/snmp/zxAnGponRmWanIpConfTable/
Authorization: Bearer {{token}}

### ONU Manager > WAN Service Configurations > ONU Service WAN IP Configuration > New
POST http://localhost/api/snmp/zxAnGponRmWanIpConfTable/285278721.1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "zxAnGponRmWanVlanPrf": "PROFILE1",
    "zxAnGponRmWanIpMode": 3,
    "zxAnGponRmWanPppoeAuthMode": 1,
    "zxAnGponRmWanPppoeUsername": "pppoe-test",
    "zxAnGponRmWanPppoePassword": "pppoe",
    "zxAnGponRmWanPppoeServiceName": "",
    "zxAnGponRmWanRspPing": 1,
    "zxAnGponRmWanRspTraceRoute": 1,
    "zxAnGponRmWanIpConfRowStatus": 4
}






### ONU Manager > PON Service Configurations > UNI VLAN
GET http://localhost/api/snmp/zxAnGponRmVlanPortTable
Authorization: Bearer {{token}}






###
GET http://localhost/api/snmp/system/0
Authorization: Bearer {{token}}

###
POST http://localhost/api/snmp/system/0
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sysContact": "+62858-6009-4649",
    "sysName": "ZXAN",
    "sysLocation": "Summarecon Bandung, Ruby Commercial 188, Kota Bandung, Jawa Barat 44173"
}






### other

### Details of ONU > Line Attributes
GET http://localhost/api/snmp/zxAnGponSrvOnuStatusTable
Authorization: Bearer {{token}}

### Details of ONU > Service Attributes
GET http://localhost/api/snmp/zxAnGponRmOnuTable
Authorization: Bearer {{token}}

### Details of ONU > Service Attributes
GET http://localhost/api/snmp/zxAnGponRmOnuCapabilityTable
Authorization: Bearer {{token}}

### Details of ONU > Performance
GET http://localhost/api/snmp/zxAnPonOnuIfCurrPerfTable
Authorization: Bearer {{token}}
