@_id=session1


### Manajemen client whatsapp
### _id - gunakan id unik untuk penanganan multi whatsapp, sebaiknya gunakan nomor whatsapp biar mudah
### connectionUpdateWebhook - end point untuk menerima data ketika connection Update
### messagesUpsertWebhook - end point untuk menerima data ketika messages Upsert
### autoStart - jalankan whatsapp otomatis ketika sistem dimulai


### tambahkan whatsapp
POST http://localhost/api/whatsapp/
Content-Type: application/json

{
"_id": "session1",
"connectionUpdateWebhook": "http://127.0.0.1/api/whatsapp/connection-update",
"messagesUpsertWebhook": "http://127.0.0.1/api/whatsapp/messages-upsert"
}


### Ambil semua data yang disimpan
GET http://localhost/api/whatsapp/

### Ambil berdasarkan _id
GET http://localhost/api/whatsapp/{{_id}}

### Ubah config yang disimpan
PATCH http://localhost/api/whatsapp/{{_id}}
Content-Type: application/json

{
    "autoStart":true
}

### Hapus data whatsapp termasuk session
DELETE http://localhost/api/whatsapp/{{_id}}








### Mulai whatsapp
POST http://localhost/api/whatsapp/start/{{_id}}
Content-Type: application/json

{
}


### Hentikan whatsapp
POST http://localhost/api/whatsapp/close/{{_id}}
Content-Type: application/json

{
}







### Kirim pesan text
POST http://localhost/api/whatsapp/send-message/{{_id}}
Content-Type: application/json

{
    "jid":"6281935155404@s.whatsapp.net",
    "content":{
        "text":"hello word"
    }
}

### Kirim pesan text (groups)
POST http://localhost/api/whatsapp/send-message/{{_id}}
Content-Type: application/json

{
    "jid":"120363393409997601@g.us",
    "content":{
        "text":"hello word"
    }
}


### logout
POST http://localhost/api/whatsapp/logout/{{_id}}
Content-Type: application/json 

{}


### end
POST http://localhost/api/whatsapp/end/{{_id}}
Content-Type: application/json 

{}


### get chats
GET http://localhost/api/whatsapp/store/chats/{{_id}}

### get contacts
GET http://localhost/api/whatsapp/store/contacts/{{_id}}

### get messages
GET http://localhost/api/whatsapp/store/messages/{{_id}}

### get groupMetadata
GET http://localhost/api/whatsapp/store/groupMetadata/{{_id}}

### get state
GET http://localhost/api/whatsapp/store/state/{{_id}}

### get presences
GET http://localhost/api/whatsapp/store/presences/{{_id}}

### get labels
GET http://localhost/api/whatsapp/store/labels/{{_id}}

### get labelAssociations
GET http://localhost/api/whatsapp/store/labelAssociations/{{_id}}


### get loadMessages
GET http://localhost/api/whatsapp/store/loadMessages/{{_id}}
?jid=6281935155404@s.whatsapp.net
&count=1
&cursor=



### get getLabels
GET http://localhost/api/whatsapp/store/getLabels/{{_id}}




### get getChatLabels
GET http://localhost/api/whatsapp/store/getChatLabels/{{_id}}
&?chatId=



### get getMessageLabels
GET http://localhost/api/whatsapp/store/getMessageLabels/{{_id}}
&?messageId=



### get loadMessage
GET http://localhost/api/whatsapp/store/loadMessage/{{_id}}
?jid=6281935155404@s.whatsapp.net
&id=



### get mostRecentMessage
GET http://localhost/api/whatsapp/store/mostRecentMessage/{{_id}}
?jid=6281935155404@s.whatsapp.net



### get fetchImageUrl
GET http://localhost/api/whatsapp/store/fetchImageUrl/{{_id}}
?jid=6281935155404@s.whatsapp.net



### get fetchGroupMetadata
GET http://localhost/api/whatsapp/store/fetchGroupMetadata/{{_id}}
?jid=6281935155404@s.whatsapp.net



### get fetchMessageReceipts
GET http://localhost/api/whatsapp/store/fetchMessageReceipts/{{_id}}
?remoteJid=6281935155404@s.whatsapp.net
&id=


